
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Bags` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Bags
 * 
 */
export type BagsModel = runtime.Types.Result.DefaultSelection<Prisma.$BagsPayload>

export type AggregateBags = {
  _count: BagsCountAggregateOutputType | null
  _min: BagsMinAggregateOutputType | null
  _max: BagsMaxAggregateOutputType | null
}

export type BagsMinAggregateOutputType = {
  bag_id: string | null
  bag_name: string | null
  description: string | null
  owner_id: string | null
}

export type BagsMaxAggregateOutputType = {
  bag_id: string | null
  bag_name: string | null
  description: string | null
  owner_id: string | null
}

export type BagsCountAggregateOutputType = {
  bag_id: number
  bag_name: number
  description: number
  owner_id: number
  _all: number
}


export type BagsMinAggregateInputType = {
  bag_id?: true
  bag_name?: true
  description?: true
  owner_id?: true
}

export type BagsMaxAggregateInputType = {
  bag_id?: true
  bag_name?: true
  description?: true
  owner_id?: true
}

export type BagsCountAggregateInputType = {
  bag_id?: true
  bag_name?: true
  description?: true
  owner_id?: true
  _all?: true
}

export type BagsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bags to aggregate.
   */
  where?: Prisma.BagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagsOrderByWithRelationInput | Prisma.BagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Bags
  **/
  _count?: true | BagsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BagsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BagsMaxAggregateInputType
}

export type GetBagsAggregateType<T extends BagsAggregateArgs> = {
      [P in keyof T & keyof AggregateBags]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBags[P]>
    : Prisma.GetScalarType<T[P], AggregateBags[P]>
}




export type BagsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BagsWhereInput
  orderBy?: Prisma.BagsOrderByWithAggregationInput | Prisma.BagsOrderByWithAggregationInput[]
  by: Prisma.BagsScalarFieldEnum[] | Prisma.BagsScalarFieldEnum
  having?: Prisma.BagsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BagsCountAggregateInputType | true
  _min?: BagsMinAggregateInputType
  _max?: BagsMaxAggregateInputType
}

export type BagsGroupByOutputType = {
  bag_id: string
  bag_name: string
  description: string
  owner_id: string | null
  _count: BagsCountAggregateOutputType | null
  _min: BagsMinAggregateOutputType | null
  _max: BagsMaxAggregateOutputType | null
}

type GetBagsGroupByPayload<T extends BagsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BagsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BagsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BagsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BagsGroupByOutputType[P]>
      }
    >
  >



export type BagsWhereInput = {
  AND?: Prisma.BagsWhereInput | Prisma.BagsWhereInput[]
  OR?: Prisma.BagsWhereInput[]
  NOT?: Prisma.BagsWhereInput | Prisma.BagsWhereInput[]
  bag_id?: Prisma.StringFilter<"Bags"> | string
  bag_name?: Prisma.StringFilter<"Bags"> | string
  description?: Prisma.StringFilter<"Bags"> | string
  owner_id?: Prisma.StringNullableFilter<"Bags"> | string | null
  recipe_bags?: Prisma.Recipe_bagsListRelationFilter
  tiddlers?: Prisma.TiddlersListRelationFilter
  acl?: Prisma.BagAclListRelationFilter
}

export type BagsOrderByWithRelationInput = {
  bag_id?: Prisma.SortOrder
  bag_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrderInput | Prisma.SortOrder
  recipe_bags?: Prisma.Recipe_bagsOrderByRelationAggregateInput
  tiddlers?: Prisma.TiddlersOrderByRelationAggregateInput
  acl?: Prisma.BagAclOrderByRelationAggregateInput
}

export type BagsWhereUniqueInput = Prisma.AtLeast<{
  bag_id?: string
  bag_name?: string
  AND?: Prisma.BagsWhereInput | Prisma.BagsWhereInput[]
  OR?: Prisma.BagsWhereInput[]
  NOT?: Prisma.BagsWhereInput | Prisma.BagsWhereInput[]
  description?: Prisma.StringFilter<"Bags"> | string
  owner_id?: Prisma.StringNullableFilter<"Bags"> | string | null
  recipe_bags?: Prisma.Recipe_bagsListRelationFilter
  tiddlers?: Prisma.TiddlersListRelationFilter
  acl?: Prisma.BagAclListRelationFilter
}, "bag_id" | "bag_name">

export type BagsOrderByWithAggregationInput = {
  bag_id?: Prisma.SortOrder
  bag_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BagsCountOrderByAggregateInput
  _max?: Prisma.BagsMaxOrderByAggregateInput
  _min?: Prisma.BagsMinOrderByAggregateInput
}

export type BagsScalarWhereWithAggregatesInput = {
  AND?: Prisma.BagsScalarWhereWithAggregatesInput | Prisma.BagsScalarWhereWithAggregatesInput[]
  OR?: Prisma.BagsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BagsScalarWhereWithAggregatesInput | Prisma.BagsScalarWhereWithAggregatesInput[]
  bag_id?: Prisma.StringWithAggregatesFilter<"Bags"> | string
  bag_name?: Prisma.StringWithAggregatesFilter<"Bags"> | string
  description?: Prisma.StringWithAggregatesFilter<"Bags"> | string
  owner_id?: Prisma.StringNullableWithAggregatesFilter<"Bags"> | string | null
}

export type BagsCreateInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  recipe_bags?: Prisma.Recipe_bagsCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlersCreateNestedManyWithoutBagInput
  acl?: Prisma.BagAclCreateNestedManyWithoutBagInput
}

export type BagsUncheckedCreateInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlersUncheckedCreateNestedManyWithoutBagInput
  acl?: Prisma.BagAclUncheckedCreateNestedManyWithoutBagInput
}

export type BagsUpdateInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlersUpdateManyWithoutBagNestedInput
  acl?: Prisma.BagAclUpdateManyWithoutBagNestedInput
}

export type BagsUncheckedUpdateInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlersUncheckedUpdateManyWithoutBagNestedInput
  acl?: Prisma.BagAclUncheckedUpdateManyWithoutBagNestedInput
}

export type BagsCreateManyInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
}

export type BagsUpdateManyMutationInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BagsUncheckedUpdateManyInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BagsScalarRelationFilter = {
  is?: Prisma.BagsWhereInput
  isNot?: Prisma.BagsWhereInput
}

export type BagsCountOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  bag_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
}

export type BagsMaxOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  bag_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
}

export type BagsMinOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  bag_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
}

export type BagsCreateNestedOneWithoutRecipe_bagsInput = {
  create?: Prisma.XOR<Prisma.BagsCreateWithoutRecipe_bagsInput, Prisma.BagsUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.BagsCreateOrConnectWithoutRecipe_bagsInput
  connect?: Prisma.BagsWhereUniqueInput
}

export type BagsUpdateOneRequiredWithoutRecipe_bagsNestedInput = {
  create?: Prisma.XOR<Prisma.BagsCreateWithoutRecipe_bagsInput, Prisma.BagsUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.BagsCreateOrConnectWithoutRecipe_bagsInput
  upsert?: Prisma.BagsUpsertWithoutRecipe_bagsInput
  connect?: Prisma.BagsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagsUpdateToOneWithWhereWithoutRecipe_bagsInput, Prisma.BagsUpdateWithoutRecipe_bagsInput>, Prisma.BagsUncheckedUpdateWithoutRecipe_bagsInput>
}

export type BagsCreateNestedOneWithoutAclInput = {
  create?: Prisma.XOR<Prisma.BagsCreateWithoutAclInput, Prisma.BagsUncheckedCreateWithoutAclInput>
  connectOrCreate?: Prisma.BagsCreateOrConnectWithoutAclInput
  connect?: Prisma.BagsWhereUniqueInput
}

export type BagsUpdateOneRequiredWithoutAclNestedInput = {
  create?: Prisma.XOR<Prisma.BagsCreateWithoutAclInput, Prisma.BagsUncheckedCreateWithoutAclInput>
  connectOrCreate?: Prisma.BagsCreateOrConnectWithoutAclInput
  upsert?: Prisma.BagsUpsertWithoutAclInput
  connect?: Prisma.BagsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagsUpdateToOneWithWhereWithoutAclInput, Prisma.BagsUpdateWithoutAclInput>, Prisma.BagsUncheckedUpdateWithoutAclInput>
}

export type BagsCreateNestedOneWithoutTiddlersInput = {
  create?: Prisma.XOR<Prisma.BagsCreateWithoutTiddlersInput, Prisma.BagsUncheckedCreateWithoutTiddlersInput>
  connectOrCreate?: Prisma.BagsCreateOrConnectWithoutTiddlersInput
  connect?: Prisma.BagsWhereUniqueInput
}

export type BagsUpdateOneRequiredWithoutTiddlersNestedInput = {
  create?: Prisma.XOR<Prisma.BagsCreateWithoutTiddlersInput, Prisma.BagsUncheckedCreateWithoutTiddlersInput>
  connectOrCreate?: Prisma.BagsCreateOrConnectWithoutTiddlersInput
  upsert?: Prisma.BagsUpsertWithoutTiddlersInput
  connect?: Prisma.BagsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagsUpdateToOneWithWhereWithoutTiddlersInput, Prisma.BagsUpdateWithoutTiddlersInput>, Prisma.BagsUncheckedUpdateWithoutTiddlersInput>
}

export type BagsCreateWithoutRecipe_bagsInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  tiddlers?: Prisma.TiddlersCreateNestedManyWithoutBagInput
  acl?: Prisma.BagAclCreateNestedManyWithoutBagInput
}

export type BagsUncheckedCreateWithoutRecipe_bagsInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  tiddlers?: Prisma.TiddlersUncheckedCreateNestedManyWithoutBagInput
  acl?: Prisma.BagAclUncheckedCreateNestedManyWithoutBagInput
}

export type BagsCreateOrConnectWithoutRecipe_bagsInput = {
  where: Prisma.BagsWhereUniqueInput
  create: Prisma.XOR<Prisma.BagsCreateWithoutRecipe_bagsInput, Prisma.BagsUncheckedCreateWithoutRecipe_bagsInput>
}

export type BagsUpsertWithoutRecipe_bagsInput = {
  update: Prisma.XOR<Prisma.BagsUpdateWithoutRecipe_bagsInput, Prisma.BagsUncheckedUpdateWithoutRecipe_bagsInput>
  create: Prisma.XOR<Prisma.BagsCreateWithoutRecipe_bagsInput, Prisma.BagsUncheckedCreateWithoutRecipe_bagsInput>
  where?: Prisma.BagsWhereInput
}

export type BagsUpdateToOneWithWhereWithoutRecipe_bagsInput = {
  where?: Prisma.BagsWhereInput
  data: Prisma.XOR<Prisma.BagsUpdateWithoutRecipe_bagsInput, Prisma.BagsUncheckedUpdateWithoutRecipe_bagsInput>
}

export type BagsUpdateWithoutRecipe_bagsInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiddlers?: Prisma.TiddlersUpdateManyWithoutBagNestedInput
  acl?: Prisma.BagAclUpdateManyWithoutBagNestedInput
}

export type BagsUncheckedUpdateWithoutRecipe_bagsInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiddlers?: Prisma.TiddlersUncheckedUpdateManyWithoutBagNestedInput
  acl?: Prisma.BagAclUncheckedUpdateManyWithoutBagNestedInput
}

export type BagsCreateWithoutAclInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  recipe_bags?: Prisma.Recipe_bagsCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlersCreateNestedManyWithoutBagInput
}

export type BagsUncheckedCreateWithoutAclInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlersUncheckedCreateNestedManyWithoutBagInput
}

export type BagsCreateOrConnectWithoutAclInput = {
  where: Prisma.BagsWhereUniqueInput
  create: Prisma.XOR<Prisma.BagsCreateWithoutAclInput, Prisma.BagsUncheckedCreateWithoutAclInput>
}

export type BagsUpsertWithoutAclInput = {
  update: Prisma.XOR<Prisma.BagsUpdateWithoutAclInput, Prisma.BagsUncheckedUpdateWithoutAclInput>
  create: Prisma.XOR<Prisma.BagsCreateWithoutAclInput, Prisma.BagsUncheckedCreateWithoutAclInput>
  where?: Prisma.BagsWhereInput
}

export type BagsUpdateToOneWithWhereWithoutAclInput = {
  where?: Prisma.BagsWhereInput
  data: Prisma.XOR<Prisma.BagsUpdateWithoutAclInput, Prisma.BagsUncheckedUpdateWithoutAclInput>
}

export type BagsUpdateWithoutAclInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlersUpdateManyWithoutBagNestedInput
}

export type BagsUncheckedUpdateWithoutAclInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlersUncheckedUpdateManyWithoutBagNestedInput
}

export type BagsCreateWithoutTiddlersInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  recipe_bags?: Prisma.Recipe_bagsCreateNestedManyWithoutBagInput
  acl?: Prisma.BagAclCreateNestedManyWithoutBagInput
}

export type BagsUncheckedCreateWithoutTiddlersInput = {
  bag_id?: string
  bag_name: string
  description: string
  owner_id?: string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedCreateNestedManyWithoutBagInput
  acl?: Prisma.BagAclUncheckedCreateNestedManyWithoutBagInput
}

export type BagsCreateOrConnectWithoutTiddlersInput = {
  where: Prisma.BagsWhereUniqueInput
  create: Prisma.XOR<Prisma.BagsCreateWithoutTiddlersInput, Prisma.BagsUncheckedCreateWithoutTiddlersInput>
}

export type BagsUpsertWithoutTiddlersInput = {
  update: Prisma.XOR<Prisma.BagsUpdateWithoutTiddlersInput, Prisma.BagsUncheckedUpdateWithoutTiddlersInput>
  create: Prisma.XOR<Prisma.BagsCreateWithoutTiddlersInput, Prisma.BagsUncheckedCreateWithoutTiddlersInput>
  where?: Prisma.BagsWhereInput
}

export type BagsUpdateToOneWithWhereWithoutTiddlersInput = {
  where?: Prisma.BagsWhereInput
  data: Prisma.XOR<Prisma.BagsUpdateWithoutTiddlersInput, Prisma.BagsUncheckedUpdateWithoutTiddlersInput>
}

export type BagsUpdateWithoutTiddlersInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUpdateManyWithoutBagNestedInput
  acl?: Prisma.BagAclUpdateManyWithoutBagNestedInput
}

export type BagsUncheckedUpdateWithoutTiddlersInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedUpdateManyWithoutBagNestedInput
  acl?: Prisma.BagAclUncheckedUpdateManyWithoutBagNestedInput
}


/**
 * Count Type BagsCountOutputType
 */

export type BagsCountOutputType = {
  recipe_bags: number
  tiddlers: number
  acl: number
}

export type BagsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_bags?: boolean | BagsCountOutputTypeCountRecipe_bagsArgs
  tiddlers?: boolean | BagsCountOutputTypeCountTiddlersArgs
  acl?: boolean | BagsCountOutputTypeCountAclArgs
}

/**
 * BagsCountOutputType without action
 */
export type BagsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagsCountOutputType
   */
  select?: Prisma.BagsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BagsCountOutputType without action
 */
export type BagsCountOutputTypeCountRecipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Recipe_bagsWhereInput
}

/**
 * BagsCountOutputType without action
 */
export type BagsCountOutputTypeCountTiddlersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiddlersWhereInput
}

/**
 * BagsCountOutputType without action
 */
export type BagsCountOutputTypeCountAclArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BagAclWhereInput
}


export type BagsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  bag_name?: boolean
  description?: boolean
  owner_id?: boolean
  recipe_bags?: boolean | Prisma.Bags$recipe_bagsArgs<ExtArgs>
  tiddlers?: boolean | Prisma.Bags$tiddlersArgs<ExtArgs>
  acl?: boolean | Prisma.Bags$aclArgs<ExtArgs>
  _count?: boolean | Prisma.BagsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bags"]>

export type BagsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  bag_name?: boolean
  description?: boolean
  owner_id?: boolean
}, ExtArgs["result"]["bags"]>

export type BagsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  bag_name?: boolean
  description?: boolean
  owner_id?: boolean
}, ExtArgs["result"]["bags"]>

export type BagsSelectScalar = {
  bag_id?: boolean
  bag_name?: boolean
  description?: boolean
  owner_id?: boolean
}

export type BagsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"bag_id" | "bag_name" | "description" | "owner_id", ExtArgs["result"]["bags"]>
export type BagsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_bags?: boolean | Prisma.Bags$recipe_bagsArgs<ExtArgs>
  tiddlers?: boolean | Prisma.Bags$tiddlersArgs<ExtArgs>
  acl?: boolean | Prisma.Bags$aclArgs<ExtArgs>
  _count?: boolean | Prisma.BagsCountOutputTypeDefaultArgs<ExtArgs>
}
export type BagsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type BagsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $BagsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Bags"
  objects: {
    recipe_bags: Prisma.$Recipe_bagsPayload<ExtArgs>[]
    tiddlers: Prisma.$TiddlersPayload<ExtArgs>[]
    acl: Prisma.$BagAclPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    bag_id: string
    bag_name: string
    description: string
    owner_id: string | null
  }, ExtArgs["result"]["bags"]>
  composites: {}
}

export type BagsGetPayload<S extends boolean | null | undefined | BagsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BagsPayload, S>

export type BagsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BagsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BagsCountAggregateInputType | true
  }

export interface BagsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Bags'], meta: { name: 'Bags' } }
  /**
   * Find zero or one Bags that matches the filter.
   * @param {BagsFindUniqueArgs} args - Arguments to find a Bags
   * @example
   * // Get one Bags
   * const bags = await prisma.bags.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BagsFindUniqueArgs>(args: Prisma.SelectSubset<T, BagsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Bags that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BagsFindUniqueOrThrowArgs} args - Arguments to find a Bags
   * @example
   * // Get one Bags
   * const bags = await prisma.bags.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BagsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BagsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsFindFirstArgs} args - Arguments to find a Bags
   * @example
   * // Get one Bags
   * const bags = await prisma.bags.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BagsFindFirstArgs>(args?: Prisma.SelectSubset<T, BagsFindFirstArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bags that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsFindFirstOrThrowArgs} args - Arguments to find a Bags
   * @example
   * // Get one Bags
   * const bags = await prisma.bags.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BagsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BagsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Bags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Bags
   * const bags = await prisma.bags.findMany()
   * 
   * // Get first 10 Bags
   * const bags = await prisma.bags.findMany({ take: 10 })
   * 
   * // Only select the `bag_id`
   * const bagsWithBag_idOnly = await prisma.bags.findMany({ select: { bag_id: true } })
   * 
   */
  findMany<T extends BagsFindManyArgs>(args?: Prisma.SelectSubset<T, BagsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Bags.
   * @param {BagsCreateArgs} args - Arguments to create a Bags.
   * @example
   * // Create one Bags
   * const Bags = await prisma.bags.create({
   *   data: {
   *     // ... data to create a Bags
   *   }
   * })
   * 
   */
  create<T extends BagsCreateArgs>(args: Prisma.SelectSubset<T, BagsCreateArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Bags.
   * @param {BagsCreateManyArgs} args - Arguments to create many Bags.
   * @example
   * // Create many Bags
   * const bags = await prisma.bags.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BagsCreateManyArgs>(args?: Prisma.SelectSubset<T, BagsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Bags and returns the data saved in the database.
   * @param {BagsCreateManyAndReturnArgs} args - Arguments to create many Bags.
   * @example
   * // Create many Bags
   * const bags = await prisma.bags.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Bags and only return the `bag_id`
   * const bagsWithBag_idOnly = await prisma.bags.createManyAndReturn({
   *   select: { bag_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BagsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BagsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Bags.
   * @param {BagsDeleteArgs} args - Arguments to delete one Bags.
   * @example
   * // Delete one Bags
   * const Bags = await prisma.bags.delete({
   *   where: {
   *     // ... filter to delete one Bags
   *   }
   * })
   * 
   */
  delete<T extends BagsDeleteArgs>(args: Prisma.SelectSubset<T, BagsDeleteArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Bags.
   * @param {BagsUpdateArgs} args - Arguments to update one Bags.
   * @example
   * // Update one Bags
   * const bags = await prisma.bags.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BagsUpdateArgs>(args: Prisma.SelectSubset<T, BagsUpdateArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Bags.
   * @param {BagsDeleteManyArgs} args - Arguments to filter Bags to delete.
   * @example
   * // Delete a few Bags
   * const { count } = await prisma.bags.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BagsDeleteManyArgs>(args?: Prisma.SelectSubset<T, BagsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Bags
   * const bags = await prisma.bags.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BagsUpdateManyArgs>(args: Prisma.SelectSubset<T, BagsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bags and returns the data updated in the database.
   * @param {BagsUpdateManyAndReturnArgs} args - Arguments to update many Bags.
   * @example
   * // Update many Bags
   * const bags = await prisma.bags.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Bags and only return the `bag_id`
   * const bagsWithBag_idOnly = await prisma.bags.updateManyAndReturn({
   *   select: { bag_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BagsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BagsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Bags.
   * @param {BagsUpsertArgs} args - Arguments to update or create a Bags.
   * @example
   * // Update or create a Bags
   * const bags = await prisma.bags.upsert({
   *   create: {
   *     // ... data to create a Bags
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Bags we want to update
   *   }
   * })
   */
  upsert<T extends BagsUpsertArgs>(args: Prisma.SelectSubset<T, BagsUpsertArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsCountArgs} args - Arguments to filter Bags to count.
   * @example
   * // Count the number of Bags
   * const count = await prisma.bags.count({
   *   where: {
   *     // ... the filter for the Bags we want to count
   *   }
   * })
  **/
  count<T extends BagsCountArgs>(
    args?: Prisma.Subset<T, BagsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BagsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BagsAggregateArgs>(args: Prisma.Subset<T, BagsAggregateArgs>): Prisma.PrismaPromise<GetBagsAggregateType<T>>

  /**
   * Group by Bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BagsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BagsGroupByArgs['orderBy'] }
      : { orderBy?: BagsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BagsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBagsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Bags model
 */
readonly fields: BagsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Bags.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BagsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe_bags<T extends Prisma.Bags$recipe_bagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bags$recipe_bagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tiddlers<T extends Prisma.Bags$tiddlersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bags$tiddlersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  acl<T extends Prisma.Bags$aclArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bags$aclArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagAclPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Bags model
 */
export interface BagsFieldRefs {
  readonly bag_id: Prisma.FieldRef<"Bags", 'String'>
  readonly bag_name: Prisma.FieldRef<"Bags", 'String'>
  readonly description: Prisma.FieldRef<"Bags", 'String'>
  readonly owner_id: Prisma.FieldRef<"Bags", 'String'>
}
    

// Custom InputTypes
/**
 * Bags findUnique
 */
export type BagsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * Filter, which Bags to fetch.
   */
  where: Prisma.BagsWhereUniqueInput
}

/**
 * Bags findUniqueOrThrow
 */
export type BagsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * Filter, which Bags to fetch.
   */
  where: Prisma.BagsWhereUniqueInput
}

/**
 * Bags findFirst
 */
export type BagsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * Filter, which Bags to fetch.
   */
  where?: Prisma.BagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagsOrderByWithRelationInput | Prisma.BagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bags.
   */
  cursor?: Prisma.BagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bags.
   */
  distinct?: Prisma.BagsScalarFieldEnum | Prisma.BagsScalarFieldEnum[]
}

/**
 * Bags findFirstOrThrow
 */
export type BagsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * Filter, which Bags to fetch.
   */
  where?: Prisma.BagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagsOrderByWithRelationInput | Prisma.BagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bags.
   */
  cursor?: Prisma.BagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bags.
   */
  distinct?: Prisma.BagsScalarFieldEnum | Prisma.BagsScalarFieldEnum[]
}

/**
 * Bags findMany
 */
export type BagsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * Filter, which Bags to fetch.
   */
  where?: Prisma.BagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagsOrderByWithRelationInput | Prisma.BagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Bags.
   */
  cursor?: Prisma.BagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  distinct?: Prisma.BagsScalarFieldEnum | Prisma.BagsScalarFieldEnum[]
}

/**
 * Bags create
 */
export type BagsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * The data needed to create a Bags.
   */
  data: Prisma.XOR<Prisma.BagsCreateInput, Prisma.BagsUncheckedCreateInput>
}

/**
 * Bags createMany
 */
export type BagsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Bags.
   */
  data: Prisma.BagsCreateManyInput | Prisma.BagsCreateManyInput[]
}

/**
 * Bags createManyAndReturn
 */
export type BagsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * The data used to create many Bags.
   */
  data: Prisma.BagsCreateManyInput | Prisma.BagsCreateManyInput[]
}

/**
 * Bags update
 */
export type BagsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * The data needed to update a Bags.
   */
  data: Prisma.XOR<Prisma.BagsUpdateInput, Prisma.BagsUncheckedUpdateInput>
  /**
   * Choose, which Bags to update.
   */
  where: Prisma.BagsWhereUniqueInput
}

/**
 * Bags updateMany
 */
export type BagsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Bags.
   */
  data: Prisma.XOR<Prisma.BagsUpdateManyMutationInput, Prisma.BagsUncheckedUpdateManyInput>
  /**
   * Filter which Bags to update
   */
  where?: Prisma.BagsWhereInput
  /**
   * Limit how many Bags to update.
   */
  limit?: number
}

/**
 * Bags updateManyAndReturn
 */
export type BagsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * The data used to update Bags.
   */
  data: Prisma.XOR<Prisma.BagsUpdateManyMutationInput, Prisma.BagsUncheckedUpdateManyInput>
  /**
   * Filter which Bags to update
   */
  where?: Prisma.BagsWhereInput
  /**
   * Limit how many Bags to update.
   */
  limit?: number
}

/**
 * Bags upsert
 */
export type BagsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * The filter to search for the Bags to update in case it exists.
   */
  where: Prisma.BagsWhereUniqueInput
  /**
   * In case the Bags found by the `where` argument doesn't exist, create a new Bags with this data.
   */
  create: Prisma.XOR<Prisma.BagsCreateInput, Prisma.BagsUncheckedCreateInput>
  /**
   * In case the Bags was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BagsUpdateInput, Prisma.BagsUncheckedUpdateInput>
}

/**
 * Bags delete
 */
export type BagsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
  /**
   * Filter which Bags to delete.
   */
  where: Prisma.BagsWhereUniqueInput
}

/**
 * Bags deleteMany
 */
export type BagsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bags to delete
   */
  where?: Prisma.BagsWhereInput
  /**
   * Limit how many Bags to delete.
   */
  limit?: number
}

/**
 * Bags.recipe_bags
 */
export type Bags$recipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  where?: Prisma.Recipe_bagsWhereInput
  orderBy?: Prisma.Recipe_bagsOrderByWithRelationInput | Prisma.Recipe_bagsOrderByWithRelationInput[]
  cursor?: Prisma.Recipe_bagsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Recipe_bagsScalarFieldEnum | Prisma.Recipe_bagsScalarFieldEnum[]
}

/**
 * Bags.tiddlers
 */
export type Bags$tiddlersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  where?: Prisma.TiddlersWhereInput
  orderBy?: Prisma.TiddlersOrderByWithRelationInput | Prisma.TiddlersOrderByWithRelationInput[]
  cursor?: Prisma.TiddlersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TiddlersScalarFieldEnum | Prisma.TiddlersScalarFieldEnum[]
}

/**
 * Bags.acl
 */
export type Bags$aclArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagAcl
   */
  select?: Prisma.BagAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagAcl
   */
  omit?: Prisma.BagAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagAclInclude<ExtArgs> | null
  where?: Prisma.BagAclWhereInput
  orderBy?: Prisma.BagAclOrderByWithRelationInput | Prisma.BagAclOrderByWithRelationInput[]
  cursor?: Prisma.BagAclWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BagAclScalarFieldEnum | Prisma.BagAclScalarFieldEnum[]
}

/**
 * Bags without action
 */
export type BagsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bags
   */
  select?: Prisma.BagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bags
   */
  omit?: Prisma.BagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagsInclude<ExtArgs> | null
}
