
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Fields` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Fields
 * 
 */
export type FieldsModel = runtime.Types.Result.DefaultSelection<Prisma.$FieldsPayload>

export type AggregateFields = {
  _count: FieldsCountAggregateOutputType | null
  _min: FieldsMinAggregateOutputType | null
  _max: FieldsMaxAggregateOutputType | null
}

export type FieldsMinAggregateOutputType = {
  revision_id: string | null
  field_name: string | null
  field_value: string | null
}

export type FieldsMaxAggregateOutputType = {
  revision_id: string | null
  field_name: string | null
  field_value: string | null
}

export type FieldsCountAggregateOutputType = {
  revision_id: number
  field_name: number
  field_value: number
  _all: number
}


export type FieldsMinAggregateInputType = {
  revision_id?: true
  field_name?: true
  field_value?: true
}

export type FieldsMaxAggregateInputType = {
  revision_id?: true
  field_name?: true
  field_value?: true
}

export type FieldsCountAggregateInputType = {
  revision_id?: true
  field_name?: true
  field_value?: true
  _all?: true
}

export type FieldsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Fields to aggregate.
   */
  where?: Prisma.FieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldsOrderByWithRelationInput | Prisma.FieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Fields
  **/
  _count?: true | FieldsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FieldsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FieldsMaxAggregateInputType
}

export type GetFieldsAggregateType<T extends FieldsAggregateArgs> = {
      [P in keyof T & keyof AggregateFields]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFields[P]>
    : Prisma.GetScalarType<T[P], AggregateFields[P]>
}




export type FieldsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldsWhereInput
  orderBy?: Prisma.FieldsOrderByWithAggregationInput | Prisma.FieldsOrderByWithAggregationInput[]
  by: Prisma.FieldsScalarFieldEnum[] | Prisma.FieldsScalarFieldEnum
  having?: Prisma.FieldsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FieldsCountAggregateInputType | true
  _min?: FieldsMinAggregateInputType
  _max?: FieldsMaxAggregateInputType
}

export type FieldsGroupByOutputType = {
  revision_id: string
  field_name: string
  field_value: string
  _count: FieldsCountAggregateOutputType | null
  _min: FieldsMinAggregateOutputType | null
  _max: FieldsMaxAggregateOutputType | null
}

type GetFieldsGroupByPayload<T extends FieldsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FieldsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FieldsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FieldsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FieldsGroupByOutputType[P]>
      }
    >
  >



export type FieldsWhereInput = {
  AND?: Prisma.FieldsWhereInput | Prisma.FieldsWhereInput[]
  OR?: Prisma.FieldsWhereInput[]
  NOT?: Prisma.FieldsWhereInput | Prisma.FieldsWhereInput[]
  revision_id?: Prisma.StringFilter<"Fields"> | string
  field_name?: Prisma.StringFilter<"Fields"> | string
  field_value?: Prisma.StringFilter<"Fields"> | string
  tiddler?: Prisma.XOR<Prisma.TiddlersScalarRelationFilter, Prisma.TiddlersWhereInput>
}

export type FieldsOrderByWithRelationInput = {
  revision_id?: Prisma.SortOrder
  field_name?: Prisma.SortOrder
  field_value?: Prisma.SortOrder
  tiddler?: Prisma.TiddlersOrderByWithRelationInput
}

export type FieldsWhereUniqueInput = Prisma.AtLeast<{
  revision_id_field_name?: Prisma.FieldsRevision_idField_nameCompoundUniqueInput
  AND?: Prisma.FieldsWhereInput | Prisma.FieldsWhereInput[]
  OR?: Prisma.FieldsWhereInput[]
  NOT?: Prisma.FieldsWhereInput | Prisma.FieldsWhereInput[]
  revision_id?: Prisma.StringFilter<"Fields"> | string
  field_name?: Prisma.StringFilter<"Fields"> | string
  field_value?: Prisma.StringFilter<"Fields"> | string
  tiddler?: Prisma.XOR<Prisma.TiddlersScalarRelationFilter, Prisma.TiddlersWhereInput>
}, "revision_id_field_name">

export type FieldsOrderByWithAggregationInput = {
  revision_id?: Prisma.SortOrder
  field_name?: Prisma.SortOrder
  field_value?: Prisma.SortOrder
  _count?: Prisma.FieldsCountOrderByAggregateInput
  _max?: Prisma.FieldsMaxOrderByAggregateInput
  _min?: Prisma.FieldsMinOrderByAggregateInput
}

export type FieldsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FieldsScalarWhereWithAggregatesInput | Prisma.FieldsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FieldsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FieldsScalarWhereWithAggregatesInput | Prisma.FieldsScalarWhereWithAggregatesInput[]
  revision_id?: Prisma.StringWithAggregatesFilter<"Fields"> | string
  field_name?: Prisma.StringWithAggregatesFilter<"Fields"> | string
  field_value?: Prisma.StringWithAggregatesFilter<"Fields"> | string
}

export type FieldsCreateInput = {
  field_name: string
  field_value: string
  tiddler: Prisma.TiddlersCreateNestedOneWithoutFieldsInput
}

export type FieldsUncheckedCreateInput = {
  revision_id: string
  field_name: string
  field_value: string
}

export type FieldsUpdateInput = {
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
  tiddler?: Prisma.TiddlersUpdateOneRequiredWithoutFieldsNestedInput
}

export type FieldsUncheckedUpdateInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FieldsCreateManyInput = {
  revision_id: string
  field_name: string
  field_value: string
}

export type FieldsUpdateManyMutationInput = {
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FieldsUncheckedUpdateManyInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FieldsListRelationFilter = {
  every?: Prisma.FieldsWhereInput
  some?: Prisma.FieldsWhereInput
  none?: Prisma.FieldsWhereInput
}

export type FieldsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FieldsRevision_idField_nameCompoundUniqueInput = {
  revision_id: string
  field_name: string
}

export type FieldsCountOrderByAggregateInput = {
  revision_id?: Prisma.SortOrder
  field_name?: Prisma.SortOrder
  field_value?: Prisma.SortOrder
}

export type FieldsMaxOrderByAggregateInput = {
  revision_id?: Prisma.SortOrder
  field_name?: Prisma.SortOrder
  field_value?: Prisma.SortOrder
}

export type FieldsMinOrderByAggregateInput = {
  revision_id?: Prisma.SortOrder
  field_name?: Prisma.SortOrder
  field_value?: Prisma.SortOrder
}

export type FieldsCreateNestedManyWithoutTiddlerInput = {
  create?: Prisma.XOR<Prisma.FieldsCreateWithoutTiddlerInput, Prisma.FieldsUncheckedCreateWithoutTiddlerInput> | Prisma.FieldsCreateWithoutTiddlerInput[] | Prisma.FieldsUncheckedCreateWithoutTiddlerInput[]
  connectOrCreate?: Prisma.FieldsCreateOrConnectWithoutTiddlerInput | Prisma.FieldsCreateOrConnectWithoutTiddlerInput[]
  createMany?: Prisma.FieldsCreateManyTiddlerInputEnvelope
  connect?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
}

export type FieldsUncheckedCreateNestedManyWithoutTiddlerInput = {
  create?: Prisma.XOR<Prisma.FieldsCreateWithoutTiddlerInput, Prisma.FieldsUncheckedCreateWithoutTiddlerInput> | Prisma.FieldsCreateWithoutTiddlerInput[] | Prisma.FieldsUncheckedCreateWithoutTiddlerInput[]
  connectOrCreate?: Prisma.FieldsCreateOrConnectWithoutTiddlerInput | Prisma.FieldsCreateOrConnectWithoutTiddlerInput[]
  createMany?: Prisma.FieldsCreateManyTiddlerInputEnvelope
  connect?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
}

export type FieldsUpdateManyWithoutTiddlerNestedInput = {
  create?: Prisma.XOR<Prisma.FieldsCreateWithoutTiddlerInput, Prisma.FieldsUncheckedCreateWithoutTiddlerInput> | Prisma.FieldsCreateWithoutTiddlerInput[] | Prisma.FieldsUncheckedCreateWithoutTiddlerInput[]
  connectOrCreate?: Prisma.FieldsCreateOrConnectWithoutTiddlerInput | Prisma.FieldsCreateOrConnectWithoutTiddlerInput[]
  upsert?: Prisma.FieldsUpsertWithWhereUniqueWithoutTiddlerInput | Prisma.FieldsUpsertWithWhereUniqueWithoutTiddlerInput[]
  createMany?: Prisma.FieldsCreateManyTiddlerInputEnvelope
  set?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  disconnect?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  delete?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  connect?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  update?: Prisma.FieldsUpdateWithWhereUniqueWithoutTiddlerInput | Prisma.FieldsUpdateWithWhereUniqueWithoutTiddlerInput[]
  updateMany?: Prisma.FieldsUpdateManyWithWhereWithoutTiddlerInput | Prisma.FieldsUpdateManyWithWhereWithoutTiddlerInput[]
  deleteMany?: Prisma.FieldsScalarWhereInput | Prisma.FieldsScalarWhereInput[]
}

export type FieldsUncheckedUpdateManyWithoutTiddlerNestedInput = {
  create?: Prisma.XOR<Prisma.FieldsCreateWithoutTiddlerInput, Prisma.FieldsUncheckedCreateWithoutTiddlerInput> | Prisma.FieldsCreateWithoutTiddlerInput[] | Prisma.FieldsUncheckedCreateWithoutTiddlerInput[]
  connectOrCreate?: Prisma.FieldsCreateOrConnectWithoutTiddlerInput | Prisma.FieldsCreateOrConnectWithoutTiddlerInput[]
  upsert?: Prisma.FieldsUpsertWithWhereUniqueWithoutTiddlerInput | Prisma.FieldsUpsertWithWhereUniqueWithoutTiddlerInput[]
  createMany?: Prisma.FieldsCreateManyTiddlerInputEnvelope
  set?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  disconnect?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  delete?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  connect?: Prisma.FieldsWhereUniqueInput | Prisma.FieldsWhereUniqueInput[]
  update?: Prisma.FieldsUpdateWithWhereUniqueWithoutTiddlerInput | Prisma.FieldsUpdateWithWhereUniqueWithoutTiddlerInput[]
  updateMany?: Prisma.FieldsUpdateManyWithWhereWithoutTiddlerInput | Prisma.FieldsUpdateManyWithWhereWithoutTiddlerInput[]
  deleteMany?: Prisma.FieldsScalarWhereInput | Prisma.FieldsScalarWhereInput[]
}

export type FieldsCreateWithoutTiddlerInput = {
  field_name: string
  field_value: string
}

export type FieldsUncheckedCreateWithoutTiddlerInput = {
  field_name: string
  field_value: string
}

export type FieldsCreateOrConnectWithoutTiddlerInput = {
  where: Prisma.FieldsWhereUniqueInput
  create: Prisma.XOR<Prisma.FieldsCreateWithoutTiddlerInput, Prisma.FieldsUncheckedCreateWithoutTiddlerInput>
}

export type FieldsCreateManyTiddlerInputEnvelope = {
  data: Prisma.FieldsCreateManyTiddlerInput | Prisma.FieldsCreateManyTiddlerInput[]
}

export type FieldsUpsertWithWhereUniqueWithoutTiddlerInput = {
  where: Prisma.FieldsWhereUniqueInput
  update: Prisma.XOR<Prisma.FieldsUpdateWithoutTiddlerInput, Prisma.FieldsUncheckedUpdateWithoutTiddlerInput>
  create: Prisma.XOR<Prisma.FieldsCreateWithoutTiddlerInput, Prisma.FieldsUncheckedCreateWithoutTiddlerInput>
}

export type FieldsUpdateWithWhereUniqueWithoutTiddlerInput = {
  where: Prisma.FieldsWhereUniqueInput
  data: Prisma.XOR<Prisma.FieldsUpdateWithoutTiddlerInput, Prisma.FieldsUncheckedUpdateWithoutTiddlerInput>
}

export type FieldsUpdateManyWithWhereWithoutTiddlerInput = {
  where: Prisma.FieldsScalarWhereInput
  data: Prisma.XOR<Prisma.FieldsUpdateManyMutationInput, Prisma.FieldsUncheckedUpdateManyWithoutTiddlerInput>
}

export type FieldsScalarWhereInput = {
  AND?: Prisma.FieldsScalarWhereInput | Prisma.FieldsScalarWhereInput[]
  OR?: Prisma.FieldsScalarWhereInput[]
  NOT?: Prisma.FieldsScalarWhereInput | Prisma.FieldsScalarWhereInput[]
  revision_id?: Prisma.StringFilter<"Fields"> | string
  field_name?: Prisma.StringFilter<"Fields"> | string
  field_value?: Prisma.StringFilter<"Fields"> | string
}

export type FieldsCreateManyTiddlerInput = {
  field_name: string
  field_value: string
}

export type FieldsUpdateWithoutTiddlerInput = {
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FieldsUncheckedUpdateWithoutTiddlerInput = {
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FieldsUncheckedUpdateManyWithoutTiddlerInput = {
  field_name?: Prisma.StringFieldUpdateOperationsInput | string
  field_value?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FieldsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  revision_id?: boolean
  field_name?: boolean
  field_value?: boolean
  tiddler?: boolean | Prisma.TiddlersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fields"]>

export type FieldsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  revision_id?: boolean
  field_name?: boolean
  field_value?: boolean
  tiddler?: boolean | Prisma.TiddlersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fields"]>

export type FieldsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  revision_id?: boolean
  field_name?: boolean
  field_value?: boolean
  tiddler?: boolean | Prisma.TiddlersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fields"]>

export type FieldsSelectScalar = {
  revision_id?: boolean
  field_name?: boolean
  field_value?: boolean
}

export type FieldsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"revision_id" | "field_name" | "field_value", ExtArgs["result"]["fields"]>
export type FieldsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tiddler?: boolean | Prisma.TiddlersDefaultArgs<ExtArgs>
}
export type FieldsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tiddler?: boolean | Prisma.TiddlersDefaultArgs<ExtArgs>
}
export type FieldsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tiddler?: boolean | Prisma.TiddlersDefaultArgs<ExtArgs>
}

export type $FieldsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Fields"
  objects: {
    tiddler: Prisma.$TiddlersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    revision_id: string
    field_name: string
    field_value: string
  }, ExtArgs["result"]["fields"]>
  composites: {}
}

export type FieldsGetPayload<S extends boolean | null | undefined | FieldsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FieldsPayload, S>

export type FieldsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FieldsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FieldsCountAggregateInputType | true
  }

export interface FieldsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Fields'], meta: { name: 'Fields' } }
  /**
   * Find zero or one Fields that matches the filter.
   * @param {FieldsFindUniqueArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FieldsFindUniqueArgs>(args: Prisma.SelectSubset<T, FieldsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Fields that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FieldsFindUniqueOrThrowArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FieldsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FieldsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Fields that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsFindFirstArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FieldsFindFirstArgs>(args?: Prisma.SelectSubset<T, FieldsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Fields that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsFindFirstOrThrowArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FieldsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FieldsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Fields that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Fields
   * const fields = await prisma.fields.findMany()
   * 
   * // Get first 10 Fields
   * const fields = await prisma.fields.findMany({ take: 10 })
   * 
   * // Only select the `revision_id`
   * const fieldsWithRevision_idOnly = await prisma.fields.findMany({ select: { revision_id: true } })
   * 
   */
  findMany<T extends FieldsFindManyArgs>(args?: Prisma.SelectSubset<T, FieldsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Fields.
   * @param {FieldsCreateArgs} args - Arguments to create a Fields.
   * @example
   * // Create one Fields
   * const Fields = await prisma.fields.create({
   *   data: {
   *     // ... data to create a Fields
   *   }
   * })
   * 
   */
  create<T extends FieldsCreateArgs>(args: Prisma.SelectSubset<T, FieldsCreateArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Fields.
   * @param {FieldsCreateManyArgs} args - Arguments to create many Fields.
   * @example
   * // Create many Fields
   * const fields = await prisma.fields.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FieldsCreateManyArgs>(args?: Prisma.SelectSubset<T, FieldsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Fields and returns the data saved in the database.
   * @param {FieldsCreateManyAndReturnArgs} args - Arguments to create many Fields.
   * @example
   * // Create many Fields
   * const fields = await prisma.fields.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Fields and only return the `revision_id`
   * const fieldsWithRevision_idOnly = await prisma.fields.createManyAndReturn({
   *   select: { revision_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FieldsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FieldsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Fields.
   * @param {FieldsDeleteArgs} args - Arguments to delete one Fields.
   * @example
   * // Delete one Fields
   * const Fields = await prisma.fields.delete({
   *   where: {
   *     // ... filter to delete one Fields
   *   }
   * })
   * 
   */
  delete<T extends FieldsDeleteArgs>(args: Prisma.SelectSubset<T, FieldsDeleteArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Fields.
   * @param {FieldsUpdateArgs} args - Arguments to update one Fields.
   * @example
   * // Update one Fields
   * const fields = await prisma.fields.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FieldsUpdateArgs>(args: Prisma.SelectSubset<T, FieldsUpdateArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Fields.
   * @param {FieldsDeleteManyArgs} args - Arguments to filter Fields to delete.
   * @example
   * // Delete a few Fields
   * const { count } = await prisma.fields.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FieldsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FieldsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Fields
   * const fields = await prisma.fields.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FieldsUpdateManyArgs>(args: Prisma.SelectSubset<T, FieldsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Fields and returns the data updated in the database.
   * @param {FieldsUpdateManyAndReturnArgs} args - Arguments to update many Fields.
   * @example
   * // Update many Fields
   * const fields = await prisma.fields.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Fields and only return the `revision_id`
   * const fieldsWithRevision_idOnly = await prisma.fields.updateManyAndReturn({
   *   select: { revision_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FieldsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FieldsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Fields.
   * @param {FieldsUpsertArgs} args - Arguments to update or create a Fields.
   * @example
   * // Update or create a Fields
   * const fields = await prisma.fields.upsert({
   *   create: {
   *     // ... data to create a Fields
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Fields we want to update
   *   }
   * })
   */
  upsert<T extends FieldsUpsertArgs>(args: Prisma.SelectSubset<T, FieldsUpsertArgs<ExtArgs>>): Prisma.Prisma__FieldsClient<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsCountArgs} args - Arguments to filter Fields to count.
   * @example
   * // Count the number of Fields
   * const count = await prisma.fields.count({
   *   where: {
   *     // ... the filter for the Fields we want to count
   *   }
   * })
  **/
  count<T extends FieldsCountArgs>(
    args?: Prisma.Subset<T, FieldsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FieldsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FieldsAggregateArgs>(args: Prisma.Subset<T, FieldsAggregateArgs>): Prisma.PrismaPromise<GetFieldsAggregateType<T>>

  /**
   * Group by Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FieldsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FieldsGroupByArgs['orderBy'] }
      : { orderBy?: FieldsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FieldsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFieldsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Fields model
 */
readonly fields: FieldsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Fields.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FieldsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tiddler<T extends Prisma.TiddlersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TiddlersDefaultArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Fields model
 */
export interface FieldsFieldRefs {
  readonly revision_id: Prisma.FieldRef<"Fields", 'String'>
  readonly field_name: Prisma.FieldRef<"Fields", 'String'>
  readonly field_value: Prisma.FieldRef<"Fields", 'String'>
}
    

// Custom InputTypes
/**
 * Fields findUnique
 */
export type FieldsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * Filter, which Fields to fetch.
   */
  where: Prisma.FieldsWhereUniqueInput
}

/**
 * Fields findUniqueOrThrow
 */
export type FieldsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * Filter, which Fields to fetch.
   */
  where: Prisma.FieldsWhereUniqueInput
}

/**
 * Fields findFirst
 */
export type FieldsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * Filter, which Fields to fetch.
   */
  where?: Prisma.FieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldsOrderByWithRelationInput | Prisma.FieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Fields.
   */
  cursor?: Prisma.FieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fields.
   */
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * Fields findFirstOrThrow
 */
export type FieldsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * Filter, which Fields to fetch.
   */
  where?: Prisma.FieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldsOrderByWithRelationInput | Prisma.FieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Fields.
   */
  cursor?: Prisma.FieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fields.
   */
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * Fields findMany
 */
export type FieldsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * Filter, which Fields to fetch.
   */
  where?: Prisma.FieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldsOrderByWithRelationInput | Prisma.FieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Fields.
   */
  cursor?: Prisma.FieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * Fields create
 */
export type FieldsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * The data needed to create a Fields.
   */
  data: Prisma.XOR<Prisma.FieldsCreateInput, Prisma.FieldsUncheckedCreateInput>
}

/**
 * Fields createMany
 */
export type FieldsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Fields.
   */
  data: Prisma.FieldsCreateManyInput | Prisma.FieldsCreateManyInput[]
}

/**
 * Fields createManyAndReturn
 */
export type FieldsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * The data used to create many Fields.
   */
  data: Prisma.FieldsCreateManyInput | Prisma.FieldsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Fields update
 */
export type FieldsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * The data needed to update a Fields.
   */
  data: Prisma.XOR<Prisma.FieldsUpdateInput, Prisma.FieldsUncheckedUpdateInput>
  /**
   * Choose, which Fields to update.
   */
  where: Prisma.FieldsWhereUniqueInput
}

/**
 * Fields updateMany
 */
export type FieldsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Fields.
   */
  data: Prisma.XOR<Prisma.FieldsUpdateManyMutationInput, Prisma.FieldsUncheckedUpdateManyInput>
  /**
   * Filter which Fields to update
   */
  where?: Prisma.FieldsWhereInput
  /**
   * Limit how many Fields to update.
   */
  limit?: number
}

/**
 * Fields updateManyAndReturn
 */
export type FieldsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * The data used to update Fields.
   */
  data: Prisma.XOR<Prisma.FieldsUpdateManyMutationInput, Prisma.FieldsUncheckedUpdateManyInput>
  /**
   * Filter which Fields to update
   */
  where?: Prisma.FieldsWhereInput
  /**
   * Limit how many Fields to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Fields upsert
 */
export type FieldsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * The filter to search for the Fields to update in case it exists.
   */
  where: Prisma.FieldsWhereUniqueInput
  /**
   * In case the Fields found by the `where` argument doesn't exist, create a new Fields with this data.
   */
  create: Prisma.XOR<Prisma.FieldsCreateInput, Prisma.FieldsUncheckedCreateInput>
  /**
   * In case the Fields was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FieldsUpdateInput, Prisma.FieldsUncheckedUpdateInput>
}

/**
 * Fields delete
 */
export type FieldsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  /**
   * Filter which Fields to delete.
   */
  where: Prisma.FieldsWhereUniqueInput
}

/**
 * Fields deleteMany
 */
export type FieldsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Fields to delete
   */
  where?: Prisma.FieldsWhereInput
  /**
   * Limit how many Fields to delete.
   */
  limit?: number
}

/**
 * Fields without action
 */
export type FieldsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
}
