
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Recipes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Recipes
 * 
 */
export type RecipesModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipesPayload>

export type AggregateRecipes = {
  _count: RecipesCountAggregateOutputType | null
  _min: RecipesMinAggregateOutputType | null
  _max: RecipesMaxAggregateOutputType | null
}

export type RecipesMinAggregateOutputType = {
  recipe_id: string | null
  recipe_name: string | null
  description: string | null
  owner_id: string | null
  skip_required_plugins: boolean | null
  skip_core: boolean | null
  preload_store: boolean | null
  custom_wiki: string | null
}

export type RecipesMaxAggregateOutputType = {
  recipe_id: string | null
  recipe_name: string | null
  description: string | null
  owner_id: string | null
  skip_required_plugins: boolean | null
  skip_core: boolean | null
  preload_store: boolean | null
  custom_wiki: string | null
}

export type RecipesCountAggregateOutputType = {
  recipe_id: number
  recipe_name: number
  description: number
  owner_id: number
  plugin_names: number
  skip_required_plugins: number
  skip_core: number
  preload_store: number
  custom_wiki: number
  _all: number
}


export type RecipesMinAggregateInputType = {
  recipe_id?: true
  recipe_name?: true
  description?: true
  owner_id?: true
  skip_required_plugins?: true
  skip_core?: true
  preload_store?: true
  custom_wiki?: true
}

export type RecipesMaxAggregateInputType = {
  recipe_id?: true
  recipe_name?: true
  description?: true
  owner_id?: true
  skip_required_plugins?: true
  skip_core?: true
  preload_store?: true
  custom_wiki?: true
}

export type RecipesCountAggregateInputType = {
  recipe_id?: true
  recipe_name?: true
  description?: true
  owner_id?: true
  plugin_names?: true
  skip_required_plugins?: true
  skip_core?: true
  preload_store?: true
  custom_wiki?: true
  _all?: true
}

export type RecipesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Recipes to aggregate.
   */
  where?: Prisma.RecipesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipesOrderByWithRelationInput | Prisma.RecipesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Recipes
  **/
  _count?: true | RecipesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipesMaxAggregateInputType
}

export type GetRecipesAggregateType<T extends RecipesAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipes[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipes[P]>
}




export type RecipesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipesWhereInput
  orderBy?: Prisma.RecipesOrderByWithAggregationInput | Prisma.RecipesOrderByWithAggregationInput[]
  by: Prisma.RecipesScalarFieldEnum[] | Prisma.RecipesScalarFieldEnum
  having?: Prisma.RecipesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipesCountAggregateInputType | true
  _min?: RecipesMinAggregateInputType
  _max?: RecipesMaxAggregateInputType
}

export type RecipesGroupByOutputType = {
  recipe_id: string
  recipe_name: string
  description: string
  owner_id: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins: boolean
  skip_core: boolean
  preload_store: boolean
  custom_wiki: string | null
  _count: RecipesCountAggregateOutputType | null
  _min: RecipesMinAggregateOutputType | null
  _max: RecipesMaxAggregateOutputType | null
}

type GetRecipesGroupByPayload<T extends RecipesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipesGroupByOutputType[P]>
      }
    >
  >



export type RecipesWhereInput = {
  AND?: Prisma.RecipesWhereInput | Prisma.RecipesWhereInput[]
  OR?: Prisma.RecipesWhereInput[]
  NOT?: Prisma.RecipesWhereInput | Prisma.RecipesWhereInput[]
  recipe_id?: Prisma.StringFilter<"Recipes"> | string
  recipe_name?: Prisma.StringFilter<"Recipes"> | string
  description?: Prisma.StringFilter<"Recipes"> | string
  owner_id?: Prisma.StringNullableFilter<"Recipes"> | string | null
  plugin_names?: Prisma.JsonFilter<"Recipes">
  skip_required_plugins?: Prisma.BoolFilter<"Recipes"> | boolean
  skip_core?: Prisma.BoolFilter<"Recipes"> | boolean
  preload_store?: Prisma.BoolFilter<"Recipes"> | boolean
  custom_wiki?: Prisma.StringNullableFilter<"Recipes"> | string | null
  recipe_bags?: Prisma.Recipe_bagsListRelationFilter
  acl?: Prisma.RecipeAclListRelationFilter
}

export type RecipesOrderByWithRelationInput = {
  recipe_id?: Prisma.SortOrder
  recipe_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrderInput | Prisma.SortOrder
  plugin_names?: Prisma.SortOrder
  skip_required_plugins?: Prisma.SortOrder
  skip_core?: Prisma.SortOrder
  preload_store?: Prisma.SortOrder
  custom_wiki?: Prisma.SortOrderInput | Prisma.SortOrder
  recipe_bags?: Prisma.Recipe_bagsOrderByRelationAggregateInput
  acl?: Prisma.RecipeAclOrderByRelationAggregateInput
}

export type RecipesWhereUniqueInput = Prisma.AtLeast<{
  recipe_id?: string
  recipe_name?: string
  AND?: Prisma.RecipesWhereInput | Prisma.RecipesWhereInput[]
  OR?: Prisma.RecipesWhereInput[]
  NOT?: Prisma.RecipesWhereInput | Prisma.RecipesWhereInput[]
  description?: Prisma.StringFilter<"Recipes"> | string
  owner_id?: Prisma.StringNullableFilter<"Recipes"> | string | null
  plugin_names?: Prisma.JsonFilter<"Recipes">
  skip_required_plugins?: Prisma.BoolFilter<"Recipes"> | boolean
  skip_core?: Prisma.BoolFilter<"Recipes"> | boolean
  preload_store?: Prisma.BoolFilter<"Recipes"> | boolean
  custom_wiki?: Prisma.StringNullableFilter<"Recipes"> | string | null
  recipe_bags?: Prisma.Recipe_bagsListRelationFilter
  acl?: Prisma.RecipeAclListRelationFilter
}, "recipe_id" | "recipe_name">

export type RecipesOrderByWithAggregationInput = {
  recipe_id?: Prisma.SortOrder
  recipe_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrderInput | Prisma.SortOrder
  plugin_names?: Prisma.SortOrder
  skip_required_plugins?: Prisma.SortOrder
  skip_core?: Prisma.SortOrder
  preload_store?: Prisma.SortOrder
  custom_wiki?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RecipesCountOrderByAggregateInput
  _max?: Prisma.RecipesMaxOrderByAggregateInput
  _min?: Prisma.RecipesMinOrderByAggregateInput
}

export type RecipesScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipesScalarWhereWithAggregatesInput | Prisma.RecipesScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipesScalarWhereWithAggregatesInput | Prisma.RecipesScalarWhereWithAggregatesInput[]
  recipe_id?: Prisma.StringWithAggregatesFilter<"Recipes"> | string
  recipe_name?: Prisma.StringWithAggregatesFilter<"Recipes"> | string
  description?: Prisma.StringWithAggregatesFilter<"Recipes"> | string
  owner_id?: Prisma.StringNullableWithAggregatesFilter<"Recipes"> | string | null
  plugin_names?: Prisma.JsonWithAggregatesFilter<"Recipes">
  skip_required_plugins?: Prisma.BoolWithAggregatesFilter<"Recipes"> | boolean
  skip_core?: Prisma.BoolWithAggregatesFilter<"Recipes"> | boolean
  preload_store?: Prisma.BoolWithAggregatesFilter<"Recipes"> | boolean
  custom_wiki?: Prisma.StringNullableWithAggregatesFilter<"Recipes"> | string | null
}

export type RecipesCreateInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
  recipe_bags?: Prisma.Recipe_bagsCreateNestedManyWithoutRecipeInput
  acl?: Prisma.RecipeAclCreateNestedManyWithoutRecipeInput
}

export type RecipesUncheckedCreateInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedCreateNestedManyWithoutRecipeInput
  acl?: Prisma.RecipeAclUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipesUpdateInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUpdateManyWithoutRecipeNestedInput
  acl?: Prisma.RecipeAclUpdateManyWithoutRecipeNestedInput
}

export type RecipesUncheckedUpdateInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedUpdateManyWithoutRecipeNestedInput
  acl?: Prisma.RecipeAclUncheckedUpdateManyWithoutRecipeNestedInput
}

export type RecipesCreateManyInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
}

export type RecipesUpdateManyMutationInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RecipesUncheckedUpdateManyInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RecipesCountOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  recipe_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  plugin_names?: Prisma.SortOrder
  skip_required_plugins?: Prisma.SortOrder
  skip_core?: Prisma.SortOrder
  preload_store?: Prisma.SortOrder
  custom_wiki?: Prisma.SortOrder
}

export type RecipesMaxOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  recipe_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  skip_required_plugins?: Prisma.SortOrder
  skip_core?: Prisma.SortOrder
  preload_store?: Prisma.SortOrder
  custom_wiki?: Prisma.SortOrder
}

export type RecipesMinOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  recipe_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  skip_required_plugins?: Prisma.SortOrder
  skip_core?: Prisma.SortOrder
  preload_store?: Prisma.SortOrder
  custom_wiki?: Prisma.SortOrder
}

export type RecipesScalarRelationFilter = {
  is?: Prisma.RecipesWhereInput
  isNot?: Prisma.RecipesWhereInput
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type RecipesCreateNestedOneWithoutAclInput = {
  create?: Prisma.XOR<Prisma.RecipesCreateWithoutAclInput, Prisma.RecipesUncheckedCreateWithoutAclInput>
  connectOrCreate?: Prisma.RecipesCreateOrConnectWithoutAclInput
  connect?: Prisma.RecipesWhereUniqueInput
}

export type RecipesUpdateOneRequiredWithoutAclNestedInput = {
  create?: Prisma.XOR<Prisma.RecipesCreateWithoutAclInput, Prisma.RecipesUncheckedCreateWithoutAclInput>
  connectOrCreate?: Prisma.RecipesCreateOrConnectWithoutAclInput
  upsert?: Prisma.RecipesUpsertWithoutAclInput
  connect?: Prisma.RecipesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RecipesUpdateToOneWithWhereWithoutAclInput, Prisma.RecipesUpdateWithoutAclInput>, Prisma.RecipesUncheckedUpdateWithoutAclInput>
}

export type RecipesCreateNestedOneWithoutRecipe_bagsInput = {
  create?: Prisma.XOR<Prisma.RecipesCreateWithoutRecipe_bagsInput, Prisma.RecipesUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.RecipesCreateOrConnectWithoutRecipe_bagsInput
  connect?: Prisma.RecipesWhereUniqueInput
}

export type RecipesUpdateOneRequiredWithoutRecipe_bagsNestedInput = {
  create?: Prisma.XOR<Prisma.RecipesCreateWithoutRecipe_bagsInput, Prisma.RecipesUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.RecipesCreateOrConnectWithoutRecipe_bagsInput
  upsert?: Prisma.RecipesUpsertWithoutRecipe_bagsInput
  connect?: Prisma.RecipesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RecipesUpdateToOneWithWhereWithoutRecipe_bagsInput, Prisma.RecipesUpdateWithoutRecipe_bagsInput>, Prisma.RecipesUncheckedUpdateWithoutRecipe_bagsInput>
}

export type RecipesCreateWithoutAclInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
  recipe_bags?: Prisma.Recipe_bagsCreateNestedManyWithoutRecipeInput
}

export type RecipesUncheckedCreateWithoutAclInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipesCreateOrConnectWithoutAclInput = {
  where: Prisma.RecipesWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipesCreateWithoutAclInput, Prisma.RecipesUncheckedCreateWithoutAclInput>
}

export type RecipesUpsertWithoutAclInput = {
  update: Prisma.XOR<Prisma.RecipesUpdateWithoutAclInput, Prisma.RecipesUncheckedUpdateWithoutAclInput>
  create: Prisma.XOR<Prisma.RecipesCreateWithoutAclInput, Prisma.RecipesUncheckedCreateWithoutAclInput>
  where?: Prisma.RecipesWhereInput
}

export type RecipesUpdateToOneWithWhereWithoutAclInput = {
  where?: Prisma.RecipesWhereInput
  data: Prisma.XOR<Prisma.RecipesUpdateWithoutAclInput, Prisma.RecipesUncheckedUpdateWithoutAclInput>
}

export type RecipesUpdateWithoutAclInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUpdateManyWithoutRecipeNestedInput
}

export type RecipesUncheckedUpdateWithoutAclInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_bags?: Prisma.Recipe_bagsUncheckedUpdateManyWithoutRecipeNestedInput
}

export type RecipesCreateWithoutRecipe_bagsInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
  acl?: Prisma.RecipeAclCreateNestedManyWithoutRecipeInput
}

export type RecipesUncheckedCreateWithoutRecipe_bagsInput = {
  recipe_id?: string
  recipe_name: string
  description: string
  owner_id?: string | null
  plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: string | null
  acl?: Prisma.RecipeAclUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipesCreateOrConnectWithoutRecipe_bagsInput = {
  where: Prisma.RecipesWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipesCreateWithoutRecipe_bagsInput, Prisma.RecipesUncheckedCreateWithoutRecipe_bagsInput>
}

export type RecipesUpsertWithoutRecipe_bagsInput = {
  update: Prisma.XOR<Prisma.RecipesUpdateWithoutRecipe_bagsInput, Prisma.RecipesUncheckedUpdateWithoutRecipe_bagsInput>
  create: Prisma.XOR<Prisma.RecipesCreateWithoutRecipe_bagsInput, Prisma.RecipesUncheckedCreateWithoutRecipe_bagsInput>
  where?: Prisma.RecipesWhereInput
}

export type RecipesUpdateToOneWithWhereWithoutRecipe_bagsInput = {
  where?: Prisma.RecipesWhereInput
  data: Prisma.XOR<Prisma.RecipesUpdateWithoutRecipe_bagsInput, Prisma.RecipesUncheckedUpdateWithoutRecipe_bagsInput>
}

export type RecipesUpdateWithoutRecipe_bagsInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acl?: Prisma.RecipeAclUpdateManyWithoutRecipeNestedInput
}

export type RecipesUncheckedUpdateWithoutRecipe_bagsInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plugin_names?:PrismaJson.AllTypes["Recipes_plugin_names"]
  skip_required_plugins?: Prisma.BoolFieldUpdateOperationsInput | boolean
  skip_core?: Prisma.BoolFieldUpdateOperationsInput | boolean
  preload_store?: Prisma.BoolFieldUpdateOperationsInput | boolean
  custom_wiki?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acl?: Prisma.RecipeAclUncheckedUpdateManyWithoutRecipeNestedInput
}


/**
 * Count Type RecipesCountOutputType
 */

export type RecipesCountOutputType = {
  recipe_bags: number
  acl: number
}

export type RecipesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_bags?: boolean | RecipesCountOutputTypeCountRecipe_bagsArgs
  acl?: boolean | RecipesCountOutputTypeCountAclArgs
}

/**
 * RecipesCountOutputType without action
 */
export type RecipesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipesCountOutputType
   */
  select?: Prisma.RecipesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RecipesCountOutputType without action
 */
export type RecipesCountOutputTypeCountRecipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Recipe_bagsWhereInput
}

/**
 * RecipesCountOutputType without action
 */
export type RecipesCountOutputTypeCountAclArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeAclWhereInput
}


export type RecipesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  recipe_name?: boolean
  description?: boolean
  owner_id?: boolean
  plugin_names?: boolean
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: boolean
  recipe_bags?: boolean | Prisma.Recipes$recipe_bagsArgs<ExtArgs>
  acl?: boolean | Prisma.Recipes$aclArgs<ExtArgs>
  _count?: boolean | Prisma.RecipesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipes"]>

export type RecipesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  recipe_name?: boolean
  description?: boolean
  owner_id?: boolean
  plugin_names?: boolean
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: boolean
}, ExtArgs["result"]["recipes"]>

export type RecipesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  recipe_name?: boolean
  description?: boolean
  owner_id?: boolean
  plugin_names?: boolean
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: boolean
}, ExtArgs["result"]["recipes"]>

export type RecipesSelectScalar = {
  recipe_id?: boolean
  recipe_name?: boolean
  description?: boolean
  owner_id?: boolean
  plugin_names?: boolean
  skip_required_plugins?: boolean
  skip_core?: boolean
  preload_store?: boolean
  custom_wiki?: boolean
}

export type RecipesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"recipe_id" | "recipe_name" | "description" | "owner_id" | "plugin_names" | "skip_required_plugins" | "skip_core" | "preload_store" | "custom_wiki", ExtArgs["result"]["recipes"]>
export type RecipesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_bags?: boolean | Prisma.Recipes$recipe_bagsArgs<ExtArgs>
  acl?: boolean | Prisma.Recipes$aclArgs<ExtArgs>
  _count?: boolean | Prisma.RecipesCountOutputTypeDefaultArgs<ExtArgs>
}
export type RecipesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RecipesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RecipesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Recipes"
  objects: {
    recipe_bags: Prisma.$Recipe_bagsPayload<ExtArgs>[]
    acl: Prisma.$RecipeAclPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    recipe_id: string
    recipe_name: string
    description: string
    owner_id: string | null
    /**
     * [Recipes_plugin_names]
     */
    plugin_names:PrismaJson.AllTypes["Recipes_plugin_names"]
    skip_required_plugins: boolean
    skip_core: boolean
    preload_store: boolean
    custom_wiki: string | null
  }, ExtArgs["result"]["recipes"]>
  composites: {}
}

export type RecipesGetPayload<S extends boolean | null | undefined | RecipesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipesPayload, S>

export type RecipesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipesCountAggregateInputType | true
  }

export interface RecipesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Recipes'], meta: { name: 'Recipes' } }
  /**
   * Find zero or one Recipes that matches the filter.
   * @param {RecipesFindUniqueArgs} args - Arguments to find a Recipes
   * @example
   * // Get one Recipes
   * const recipes = await prisma.recipes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipesFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Recipes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipesFindUniqueOrThrowArgs} args - Arguments to find a Recipes
   * @example
   * // Get one Recipes
   * const recipes = await prisma.recipes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Recipes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesFindFirstArgs} args - Arguments to find a Recipes
   * @example
   * // Get one Recipes
   * const recipes = await prisma.recipes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipesFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipesFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Recipes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesFindFirstOrThrowArgs} args - Arguments to find a Recipes
   * @example
   * // Get one Recipes
   * const recipes = await prisma.recipes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Recipes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Recipes
   * const recipes = await prisma.recipes.findMany()
   * 
   * // Get first 10 Recipes
   * const recipes = await prisma.recipes.findMany({ take: 10 })
   * 
   * // Only select the `recipe_id`
   * const recipesWithRecipe_idOnly = await prisma.recipes.findMany({ select: { recipe_id: true } })
   * 
   */
  findMany<T extends RecipesFindManyArgs>(args?: Prisma.SelectSubset<T, RecipesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Recipes.
   * @param {RecipesCreateArgs} args - Arguments to create a Recipes.
   * @example
   * // Create one Recipes
   * const Recipes = await prisma.recipes.create({
   *   data: {
   *     // ... data to create a Recipes
   *   }
   * })
   * 
   */
  create<T extends RecipesCreateArgs>(args: Prisma.SelectSubset<T, RecipesCreateArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Recipes.
   * @param {RecipesCreateManyArgs} args - Arguments to create many Recipes.
   * @example
   * // Create many Recipes
   * const recipes = await prisma.recipes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipesCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Recipes and returns the data saved in the database.
   * @param {RecipesCreateManyAndReturnArgs} args - Arguments to create many Recipes.
   * @example
   * // Create many Recipes
   * const recipes = await prisma.recipes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Recipes and only return the `recipe_id`
   * const recipesWithRecipe_idOnly = await prisma.recipes.createManyAndReturn({
   *   select: { recipe_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Recipes.
   * @param {RecipesDeleteArgs} args - Arguments to delete one Recipes.
   * @example
   * // Delete one Recipes
   * const Recipes = await prisma.recipes.delete({
   *   where: {
   *     // ... filter to delete one Recipes
   *   }
   * })
   * 
   */
  delete<T extends RecipesDeleteArgs>(args: Prisma.SelectSubset<T, RecipesDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Recipes.
   * @param {RecipesUpdateArgs} args - Arguments to update one Recipes.
   * @example
   * // Update one Recipes
   * const recipes = await prisma.recipes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipesUpdateArgs>(args: Prisma.SelectSubset<T, RecipesUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Recipes.
   * @param {RecipesDeleteManyArgs} args - Arguments to filter Recipes to delete.
   * @example
   * // Delete a few Recipes
   * const { count } = await prisma.recipes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipesDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Recipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Recipes
   * const recipes = await prisma.recipes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipesUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Recipes and returns the data updated in the database.
   * @param {RecipesUpdateManyAndReturnArgs} args - Arguments to update many Recipes.
   * @example
   * // Update many Recipes
   * const recipes = await prisma.recipes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Recipes and only return the `recipe_id`
   * const recipesWithRecipe_idOnly = await prisma.recipes.updateManyAndReturn({
   *   select: { recipe_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Recipes.
   * @param {RecipesUpsertArgs} args - Arguments to update or create a Recipes.
   * @example
   * // Update or create a Recipes
   * const recipes = await prisma.recipes.upsert({
   *   create: {
   *     // ... data to create a Recipes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Recipes we want to update
   *   }
   * })
   */
  upsert<T extends RecipesUpsertArgs>(args: Prisma.SelectSubset<T, RecipesUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Recipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesCountArgs} args - Arguments to filter Recipes to count.
   * @example
   * // Count the number of Recipes
   * const count = await prisma.recipes.count({
   *   where: {
   *     // ... the filter for the Recipes we want to count
   *   }
   * })
  **/
  count<T extends RecipesCountArgs>(
    args?: Prisma.Subset<T, RecipesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Recipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipesAggregateArgs>(args: Prisma.Subset<T, RecipesAggregateArgs>): Prisma.PrismaPromise<GetRecipesAggregateType<T>>

  /**
   * Group by Recipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipesGroupByArgs['orderBy'] }
      : { orderBy?: RecipesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Recipes model
 */
readonly fields: RecipesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Recipes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe_bags<T extends Prisma.Recipes$recipe_bagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Recipes$recipe_bagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  acl<T extends Prisma.Recipes$aclArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Recipes$aclArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Recipes model
 */
export interface RecipesFieldRefs {
  readonly recipe_id: Prisma.FieldRef<"Recipes", 'String'>
  readonly recipe_name: Prisma.FieldRef<"Recipes", 'String'>
  readonly description: Prisma.FieldRef<"Recipes", 'String'>
  readonly owner_id: Prisma.FieldRef<"Recipes", 'String'>
  readonly plugin_names: Prisma.FieldRef<"Recipes", 'Json'>
  readonly skip_required_plugins: Prisma.FieldRef<"Recipes", 'Boolean'>
  readonly skip_core: Prisma.FieldRef<"Recipes", 'Boolean'>
  readonly preload_store: Prisma.FieldRef<"Recipes", 'Boolean'>
  readonly custom_wiki: Prisma.FieldRef<"Recipes", 'String'>
}
    

// Custom InputTypes
/**
 * Recipes findUnique
 */
export type RecipesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * Filter, which Recipes to fetch.
   */
  where: Prisma.RecipesWhereUniqueInput
}

/**
 * Recipes findUniqueOrThrow
 */
export type RecipesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * Filter, which Recipes to fetch.
   */
  where: Prisma.RecipesWhereUniqueInput
}

/**
 * Recipes findFirst
 */
export type RecipesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * Filter, which Recipes to fetch.
   */
  where?: Prisma.RecipesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipesOrderByWithRelationInput | Prisma.RecipesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Recipes.
   */
  cursor?: Prisma.RecipesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipes.
   */
  distinct?: Prisma.RecipesScalarFieldEnum | Prisma.RecipesScalarFieldEnum[]
}

/**
 * Recipes findFirstOrThrow
 */
export type RecipesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * Filter, which Recipes to fetch.
   */
  where?: Prisma.RecipesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipesOrderByWithRelationInput | Prisma.RecipesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Recipes.
   */
  cursor?: Prisma.RecipesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipes.
   */
  distinct?: Prisma.RecipesScalarFieldEnum | Prisma.RecipesScalarFieldEnum[]
}

/**
 * Recipes findMany
 */
export type RecipesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * Filter, which Recipes to fetch.
   */
  where?: Prisma.RecipesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipesOrderByWithRelationInput | Prisma.RecipesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Recipes.
   */
  cursor?: Prisma.RecipesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  distinct?: Prisma.RecipesScalarFieldEnum | Prisma.RecipesScalarFieldEnum[]
}

/**
 * Recipes create
 */
export type RecipesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * The data needed to create a Recipes.
   */
  data: Prisma.XOR<Prisma.RecipesCreateInput, Prisma.RecipesUncheckedCreateInput>
}

/**
 * Recipes createMany
 */
export type RecipesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Recipes.
   */
  data: Prisma.RecipesCreateManyInput | Prisma.RecipesCreateManyInput[]
}

/**
 * Recipes createManyAndReturn
 */
export type RecipesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * The data used to create many Recipes.
   */
  data: Prisma.RecipesCreateManyInput | Prisma.RecipesCreateManyInput[]
}

/**
 * Recipes update
 */
export type RecipesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * The data needed to update a Recipes.
   */
  data: Prisma.XOR<Prisma.RecipesUpdateInput, Prisma.RecipesUncheckedUpdateInput>
  /**
   * Choose, which Recipes to update.
   */
  where: Prisma.RecipesWhereUniqueInput
}

/**
 * Recipes updateMany
 */
export type RecipesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Recipes.
   */
  data: Prisma.XOR<Prisma.RecipesUpdateManyMutationInput, Prisma.RecipesUncheckedUpdateManyInput>
  /**
   * Filter which Recipes to update
   */
  where?: Prisma.RecipesWhereInput
  /**
   * Limit how many Recipes to update.
   */
  limit?: number
}

/**
 * Recipes updateManyAndReturn
 */
export type RecipesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * The data used to update Recipes.
   */
  data: Prisma.XOR<Prisma.RecipesUpdateManyMutationInput, Prisma.RecipesUncheckedUpdateManyInput>
  /**
   * Filter which Recipes to update
   */
  where?: Prisma.RecipesWhereInput
  /**
   * Limit how many Recipes to update.
   */
  limit?: number
}

/**
 * Recipes upsert
 */
export type RecipesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * The filter to search for the Recipes to update in case it exists.
   */
  where: Prisma.RecipesWhereUniqueInput
  /**
   * In case the Recipes found by the `where` argument doesn't exist, create a new Recipes with this data.
   */
  create: Prisma.XOR<Prisma.RecipesCreateInput, Prisma.RecipesUncheckedCreateInput>
  /**
   * In case the Recipes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipesUpdateInput, Prisma.RecipesUncheckedUpdateInput>
}

/**
 * Recipes delete
 */
export type RecipesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
  /**
   * Filter which Recipes to delete.
   */
  where: Prisma.RecipesWhereUniqueInput
}

/**
 * Recipes deleteMany
 */
export type RecipesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Recipes to delete
   */
  where?: Prisma.RecipesWhereInput
  /**
   * Limit how many Recipes to delete.
   */
  limit?: number
}

/**
 * Recipes.recipe_bags
 */
export type Recipes$recipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  where?: Prisma.Recipe_bagsWhereInput
  orderBy?: Prisma.Recipe_bagsOrderByWithRelationInput | Prisma.Recipe_bagsOrderByWithRelationInput[]
  cursor?: Prisma.Recipe_bagsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Recipe_bagsScalarFieldEnum | Prisma.Recipe_bagsScalarFieldEnum[]
}

/**
 * Recipes.acl
 */
export type Recipes$aclArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  where?: Prisma.RecipeAclWhereInput
  orderBy?: Prisma.RecipeAclOrderByWithRelationInput | Prisma.RecipeAclOrderByWithRelationInput[]
  cursor?: Prisma.RecipeAclWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipeAclScalarFieldEnum | Prisma.RecipeAclScalarFieldEnum[]
}

/**
 * Recipes without action
 */
export type RecipesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipes
   */
  select?: Prisma.RecipesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipes
   */
  omit?: Prisma.RecipesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipesInclude<ExtArgs> | null
}
