
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Recipe_bags` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Recipe_bags
 * 
 */
export type Recipe_bagsModel = runtime.Types.Result.DefaultSelection<Prisma.$Recipe_bagsPayload>

export type AggregateRecipe_bags = {
  _count: Recipe_bagsCountAggregateOutputType | null
  _avg: Recipe_bagsAvgAggregateOutputType | null
  _sum: Recipe_bagsSumAggregateOutputType | null
  _min: Recipe_bagsMinAggregateOutputType | null
  _max: Recipe_bagsMaxAggregateOutputType | null
}

export type Recipe_bagsAvgAggregateOutputType = {
  position: number | null
}

export type Recipe_bagsSumAggregateOutputType = {
  position: number | null
}

export type Recipe_bagsMinAggregateOutputType = {
  recipe_id: string | null
  bag_id: string | null
  position: number | null
  with_acl: boolean | null
  load_modules: boolean | null
}

export type Recipe_bagsMaxAggregateOutputType = {
  recipe_id: string | null
  bag_id: string | null
  position: number | null
  with_acl: boolean | null
  load_modules: boolean | null
}

export type Recipe_bagsCountAggregateOutputType = {
  recipe_id: number
  bag_id: number
  position: number
  with_acl: number
  load_modules: number
  _all: number
}


export type Recipe_bagsAvgAggregateInputType = {
  position?: true
}

export type Recipe_bagsSumAggregateInputType = {
  position?: true
}

export type Recipe_bagsMinAggregateInputType = {
  recipe_id?: true
  bag_id?: true
  position?: true
  with_acl?: true
  load_modules?: true
}

export type Recipe_bagsMaxAggregateInputType = {
  recipe_id?: true
  bag_id?: true
  position?: true
  with_acl?: true
  load_modules?: true
}

export type Recipe_bagsCountAggregateInputType = {
  recipe_id?: true
  bag_id?: true
  position?: true
  with_acl?: true
  load_modules?: true
  _all?: true
}

export type Recipe_bagsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Recipe_bags to aggregate.
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipe_bags to fetch.
   */
  orderBy?: Prisma.Recipe_bagsOrderByWithRelationInput | Prisma.Recipe_bagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Recipe_bagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipe_bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipe_bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Recipe_bags
  **/
  _count?: true | Recipe_bagsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Recipe_bagsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Recipe_bagsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Recipe_bagsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Recipe_bagsMaxAggregateInputType
}

export type GetRecipe_bagsAggregateType<T extends Recipe_bagsAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipe_bags]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipe_bags[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipe_bags[P]>
}




export type Recipe_bagsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Recipe_bagsWhereInput
  orderBy?: Prisma.Recipe_bagsOrderByWithAggregationInput | Prisma.Recipe_bagsOrderByWithAggregationInput[]
  by: Prisma.Recipe_bagsScalarFieldEnum[] | Prisma.Recipe_bagsScalarFieldEnum
  having?: Prisma.Recipe_bagsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Recipe_bagsCountAggregateInputType | true
  _avg?: Recipe_bagsAvgAggregateInputType
  _sum?: Recipe_bagsSumAggregateInputType
  _min?: Recipe_bagsMinAggregateInputType
  _max?: Recipe_bagsMaxAggregateInputType
}

export type Recipe_bagsGroupByOutputType = {
  recipe_id: string
  bag_id: string
  position: number
  with_acl: boolean
  load_modules: boolean
  _count: Recipe_bagsCountAggregateOutputType | null
  _avg: Recipe_bagsAvgAggregateOutputType | null
  _sum: Recipe_bagsSumAggregateOutputType | null
  _min: Recipe_bagsMinAggregateOutputType | null
  _max: Recipe_bagsMaxAggregateOutputType | null
}

type GetRecipe_bagsGroupByPayload<T extends Recipe_bagsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Recipe_bagsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Recipe_bagsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Recipe_bagsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Recipe_bagsGroupByOutputType[P]>
      }
    >
  >



export type Recipe_bagsWhereInput = {
  AND?: Prisma.Recipe_bagsWhereInput | Prisma.Recipe_bagsWhereInput[]
  OR?: Prisma.Recipe_bagsWhereInput[]
  NOT?: Prisma.Recipe_bagsWhereInput | Prisma.Recipe_bagsWhereInput[]
  recipe_id?: Prisma.StringFilter<"Recipe_bags"> | string
  bag_id?: Prisma.StringFilter<"Recipe_bags"> | string
  position?: Prisma.IntFilter<"Recipe_bags"> | number
  with_acl?: Prisma.BoolFilter<"Recipe_bags"> | boolean
  load_modules?: Prisma.BoolFilter<"Recipe_bags"> | boolean
  bag?: Prisma.XOR<Prisma.BagsScalarRelationFilter, Prisma.BagsWhereInput>
  recipe?: Prisma.XOR<Prisma.RecipesScalarRelationFilter, Prisma.RecipesWhereInput>
}

export type Recipe_bagsOrderByWithRelationInput = {
  recipe_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  with_acl?: Prisma.SortOrder
  load_modules?: Prisma.SortOrder
  bag?: Prisma.BagsOrderByWithRelationInput
  recipe?: Prisma.RecipesOrderByWithRelationInput
}

export type Recipe_bagsWhereUniqueInput = Prisma.AtLeast<{
  recipe_id_bag_id?: Prisma.Recipe_bagsRecipe_idBag_idCompoundUniqueInput
  AND?: Prisma.Recipe_bagsWhereInput | Prisma.Recipe_bagsWhereInput[]
  OR?: Prisma.Recipe_bagsWhereInput[]
  NOT?: Prisma.Recipe_bagsWhereInput | Prisma.Recipe_bagsWhereInput[]
  recipe_id?: Prisma.StringFilter<"Recipe_bags"> | string
  bag_id?: Prisma.StringFilter<"Recipe_bags"> | string
  position?: Prisma.IntFilter<"Recipe_bags"> | number
  with_acl?: Prisma.BoolFilter<"Recipe_bags"> | boolean
  load_modules?: Prisma.BoolFilter<"Recipe_bags"> | boolean
  bag?: Prisma.XOR<Prisma.BagsScalarRelationFilter, Prisma.BagsWhereInput>
  recipe?: Prisma.XOR<Prisma.RecipesScalarRelationFilter, Prisma.RecipesWhereInput>
}, "recipe_id_bag_id">

export type Recipe_bagsOrderByWithAggregationInput = {
  recipe_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  with_acl?: Prisma.SortOrder
  load_modules?: Prisma.SortOrder
  _count?: Prisma.Recipe_bagsCountOrderByAggregateInput
  _avg?: Prisma.Recipe_bagsAvgOrderByAggregateInput
  _max?: Prisma.Recipe_bagsMaxOrderByAggregateInput
  _min?: Prisma.Recipe_bagsMinOrderByAggregateInput
  _sum?: Prisma.Recipe_bagsSumOrderByAggregateInput
}

export type Recipe_bagsScalarWhereWithAggregatesInput = {
  AND?: Prisma.Recipe_bagsScalarWhereWithAggregatesInput | Prisma.Recipe_bagsScalarWhereWithAggregatesInput[]
  OR?: Prisma.Recipe_bagsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Recipe_bagsScalarWhereWithAggregatesInput | Prisma.Recipe_bagsScalarWhereWithAggregatesInput[]
  recipe_id?: Prisma.StringWithAggregatesFilter<"Recipe_bags"> | string
  bag_id?: Prisma.StringWithAggregatesFilter<"Recipe_bags"> | string
  position?: Prisma.IntWithAggregatesFilter<"Recipe_bags"> | number
  with_acl?: Prisma.BoolWithAggregatesFilter<"Recipe_bags"> | boolean
  load_modules?: Prisma.BoolWithAggregatesFilter<"Recipe_bags"> | boolean
}

export type Recipe_bagsCreateInput = {
  position: number
  with_acl?: boolean
  load_modules?: boolean
  bag: Prisma.BagsCreateNestedOneWithoutRecipe_bagsInput
  recipe: Prisma.RecipesCreateNestedOneWithoutRecipe_bagsInput
}

export type Recipe_bagsUncheckedCreateInput = {
  recipe_id: string
  bag_id: string
  position: number
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsUpdateInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bag?: Prisma.BagsUpdateOneRequiredWithoutRecipe_bagsNestedInput
  recipe?: Prisma.RecipesUpdateOneRequiredWithoutRecipe_bagsNestedInput
}

export type Recipe_bagsUncheckedUpdateInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Recipe_bagsCreateManyInput = {
  recipe_id: string
  bag_id: string
  position: number
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsUpdateManyMutationInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Recipe_bagsUncheckedUpdateManyInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Recipe_bagsListRelationFilter = {
  every?: Prisma.Recipe_bagsWhereInput
  some?: Prisma.Recipe_bagsWhereInput
  none?: Prisma.Recipe_bagsWhereInput
}

export type Recipe_bagsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Recipe_bagsRecipe_idBag_idCompoundUniqueInput = {
  recipe_id: string
  bag_id: string
}

export type Recipe_bagsCountOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  with_acl?: Prisma.SortOrder
  load_modules?: Prisma.SortOrder
}

export type Recipe_bagsAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type Recipe_bagsMaxOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  with_acl?: Prisma.SortOrder
  load_modules?: Prisma.SortOrder
}

export type Recipe_bagsMinOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  with_acl?: Prisma.SortOrder
  load_modules?: Prisma.SortOrder
}

export type Recipe_bagsSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type Recipe_bagsCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput> | Prisma.Recipe_bagsCreateWithoutRecipeInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput | Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.Recipe_bagsCreateManyRecipeInputEnvelope
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
}

export type Recipe_bagsUncheckedCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput> | Prisma.Recipe_bagsCreateWithoutRecipeInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput | Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.Recipe_bagsCreateManyRecipeInputEnvelope
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
}

export type Recipe_bagsUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput> | Prisma.Recipe_bagsCreateWithoutRecipeInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput | Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutRecipeInput | Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.Recipe_bagsCreateManyRecipeInputEnvelope
  set?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  disconnect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  delete?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  update?: Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutRecipeInput | Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.Recipe_bagsUpdateManyWithWhereWithoutRecipeInput | Prisma.Recipe_bagsUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.Recipe_bagsScalarWhereInput | Prisma.Recipe_bagsScalarWhereInput[]
}

export type Recipe_bagsUncheckedUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput> | Prisma.Recipe_bagsCreateWithoutRecipeInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput | Prisma.Recipe_bagsCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutRecipeInput | Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.Recipe_bagsCreateManyRecipeInputEnvelope
  set?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  disconnect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  delete?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  update?: Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutRecipeInput | Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.Recipe_bagsUpdateManyWithWhereWithoutRecipeInput | Prisma.Recipe_bagsUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.Recipe_bagsScalarWhereInput | Prisma.Recipe_bagsScalarWhereInput[]
}

export type Recipe_bagsCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutBagInput, Prisma.Recipe_bagsUncheckedCreateWithoutBagInput> | Prisma.Recipe_bagsCreateWithoutBagInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutBagInput | Prisma.Recipe_bagsCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.Recipe_bagsCreateManyBagInputEnvelope
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
}

export type Recipe_bagsUncheckedCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutBagInput, Prisma.Recipe_bagsUncheckedCreateWithoutBagInput> | Prisma.Recipe_bagsCreateWithoutBagInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutBagInput | Prisma.Recipe_bagsCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.Recipe_bagsCreateManyBagInputEnvelope
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
}

export type Recipe_bagsUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutBagInput, Prisma.Recipe_bagsUncheckedCreateWithoutBagInput> | Prisma.Recipe_bagsCreateWithoutBagInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutBagInput | Prisma.Recipe_bagsCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutBagInput | Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.Recipe_bagsCreateManyBagInputEnvelope
  set?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  disconnect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  delete?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  update?: Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutBagInput | Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.Recipe_bagsUpdateManyWithWhereWithoutBagInput | Prisma.Recipe_bagsUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.Recipe_bagsScalarWhereInput | Prisma.Recipe_bagsScalarWhereInput[]
}

export type Recipe_bagsUncheckedUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutBagInput, Prisma.Recipe_bagsUncheckedCreateWithoutBagInput> | Prisma.Recipe_bagsCreateWithoutBagInput[] | Prisma.Recipe_bagsUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.Recipe_bagsCreateOrConnectWithoutBagInput | Prisma.Recipe_bagsCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutBagInput | Prisma.Recipe_bagsUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.Recipe_bagsCreateManyBagInputEnvelope
  set?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  disconnect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  delete?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  connect?: Prisma.Recipe_bagsWhereUniqueInput | Prisma.Recipe_bagsWhereUniqueInput[]
  update?: Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutBagInput | Prisma.Recipe_bagsUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.Recipe_bagsUpdateManyWithWhereWithoutBagInput | Prisma.Recipe_bagsUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.Recipe_bagsScalarWhereInput | Prisma.Recipe_bagsScalarWhereInput[]
}

export type Recipe_bagsCreateWithoutRecipeInput = {
  position: number
  with_acl?: boolean
  load_modules?: boolean
  bag: Prisma.BagsCreateNestedOneWithoutRecipe_bagsInput
}

export type Recipe_bagsUncheckedCreateWithoutRecipeInput = {
  bag_id: string
  position: number
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsCreateOrConnectWithoutRecipeInput = {
  where: Prisma.Recipe_bagsWhereUniqueInput
  create: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput>
}

export type Recipe_bagsCreateManyRecipeInputEnvelope = {
  data: Prisma.Recipe_bagsCreateManyRecipeInput | Prisma.Recipe_bagsCreateManyRecipeInput[]
}

export type Recipe_bagsUpsertWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.Recipe_bagsWhereUniqueInput
  update: Prisma.XOR<Prisma.Recipe_bagsUpdateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedUpdateWithoutRecipeInput>
  create: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedCreateWithoutRecipeInput>
}

export type Recipe_bagsUpdateWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.Recipe_bagsWhereUniqueInput
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateWithoutRecipeInput, Prisma.Recipe_bagsUncheckedUpdateWithoutRecipeInput>
}

export type Recipe_bagsUpdateManyWithWhereWithoutRecipeInput = {
  where: Prisma.Recipe_bagsScalarWhereInput
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateManyMutationInput, Prisma.Recipe_bagsUncheckedUpdateManyWithoutRecipeInput>
}

export type Recipe_bagsScalarWhereInput = {
  AND?: Prisma.Recipe_bagsScalarWhereInput | Prisma.Recipe_bagsScalarWhereInput[]
  OR?: Prisma.Recipe_bagsScalarWhereInput[]
  NOT?: Prisma.Recipe_bagsScalarWhereInput | Prisma.Recipe_bagsScalarWhereInput[]
  recipe_id?: Prisma.StringFilter<"Recipe_bags"> | string
  bag_id?: Prisma.StringFilter<"Recipe_bags"> | string
  position?: Prisma.IntFilter<"Recipe_bags"> | number
  with_acl?: Prisma.BoolFilter<"Recipe_bags"> | boolean
  load_modules?: Prisma.BoolFilter<"Recipe_bags"> | boolean
}

export type Recipe_bagsCreateWithoutBagInput = {
  position: number
  with_acl?: boolean
  load_modules?: boolean
  recipe: Prisma.RecipesCreateNestedOneWithoutRecipe_bagsInput
}

export type Recipe_bagsUncheckedCreateWithoutBagInput = {
  recipe_id: string
  position: number
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsCreateOrConnectWithoutBagInput = {
  where: Prisma.Recipe_bagsWhereUniqueInput
  create: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutBagInput, Prisma.Recipe_bagsUncheckedCreateWithoutBagInput>
}

export type Recipe_bagsCreateManyBagInputEnvelope = {
  data: Prisma.Recipe_bagsCreateManyBagInput | Prisma.Recipe_bagsCreateManyBagInput[]
}

export type Recipe_bagsUpsertWithWhereUniqueWithoutBagInput = {
  where: Prisma.Recipe_bagsWhereUniqueInput
  update: Prisma.XOR<Prisma.Recipe_bagsUpdateWithoutBagInput, Prisma.Recipe_bagsUncheckedUpdateWithoutBagInput>
  create: Prisma.XOR<Prisma.Recipe_bagsCreateWithoutBagInput, Prisma.Recipe_bagsUncheckedCreateWithoutBagInput>
}

export type Recipe_bagsUpdateWithWhereUniqueWithoutBagInput = {
  where: Prisma.Recipe_bagsWhereUniqueInput
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateWithoutBagInput, Prisma.Recipe_bagsUncheckedUpdateWithoutBagInput>
}

export type Recipe_bagsUpdateManyWithWhereWithoutBagInput = {
  where: Prisma.Recipe_bagsScalarWhereInput
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateManyMutationInput, Prisma.Recipe_bagsUncheckedUpdateManyWithoutBagInput>
}

export type Recipe_bagsCreateManyRecipeInput = {
  bag_id: string
  position: number
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsUpdateWithoutRecipeInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bag?: Prisma.BagsUpdateOneRequiredWithoutRecipe_bagsNestedInput
}

export type Recipe_bagsUncheckedUpdateWithoutRecipeInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Recipe_bagsUncheckedUpdateManyWithoutRecipeInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Recipe_bagsCreateManyBagInput = {
  recipe_id: string
  position: number
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsUpdateWithoutBagInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recipe?: Prisma.RecipesUpdateOneRequiredWithoutRecipe_bagsNestedInput
}

export type Recipe_bagsUncheckedUpdateWithoutBagInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Recipe_bagsUncheckedUpdateManyWithoutBagInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  with_acl?: Prisma.BoolFieldUpdateOperationsInput | boolean
  load_modules?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type Recipe_bagsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  bag_id?: boolean
  position?: boolean
  with_acl?: boolean
  load_modules?: boolean
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipe_bags"]>

export type Recipe_bagsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  bag_id?: boolean
  position?: boolean
  with_acl?: boolean
  load_modules?: boolean
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipe_bags"]>

export type Recipe_bagsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  bag_id?: boolean
  position?: boolean
  with_acl?: boolean
  load_modules?: boolean
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipe_bags"]>

export type Recipe_bagsSelectScalar = {
  recipe_id?: boolean
  bag_id?: boolean
  position?: boolean
  with_acl?: boolean
  load_modules?: boolean
}

export type Recipe_bagsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"recipe_id" | "bag_id" | "position" | "with_acl" | "load_modules", ExtArgs["result"]["recipe_bags"]>
export type Recipe_bagsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}
export type Recipe_bagsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}
export type Recipe_bagsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}

export type $Recipe_bagsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Recipe_bags"
  objects: {
    bag: Prisma.$BagsPayload<ExtArgs>
    recipe: Prisma.$RecipesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    recipe_id: string
    bag_id: string
    position: number
    with_acl: boolean
    load_modules: boolean
  }, ExtArgs["result"]["recipe_bags"]>
  composites: {}
}

export type Recipe_bagsGetPayload<S extends boolean | null | undefined | Recipe_bagsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload, S>

export type Recipe_bagsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Recipe_bagsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Recipe_bagsCountAggregateInputType | true
  }

export interface Recipe_bagsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Recipe_bags'], meta: { name: 'Recipe_bags' } }
  /**
   * Find zero or one Recipe_bags that matches the filter.
   * @param {Recipe_bagsFindUniqueArgs} args - Arguments to find a Recipe_bags
   * @example
   * // Get one Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Recipe_bagsFindUniqueArgs>(args: Prisma.SelectSubset<T, Recipe_bagsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Recipe_bags that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Recipe_bagsFindUniqueOrThrowArgs} args - Arguments to find a Recipe_bags
   * @example
   * // Get one Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Recipe_bagsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Recipe_bagsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Recipe_bags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsFindFirstArgs} args - Arguments to find a Recipe_bags
   * @example
   * // Get one Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Recipe_bagsFindFirstArgs>(args?: Prisma.SelectSubset<T, Recipe_bagsFindFirstArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Recipe_bags that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsFindFirstOrThrowArgs} args - Arguments to find a Recipe_bags
   * @example
   * // Get one Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Recipe_bagsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Recipe_bagsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Recipe_bags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.findMany()
   * 
   * // Get first 10 Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.findMany({ take: 10 })
   * 
   * // Only select the `recipe_id`
   * const recipe_bagsWithRecipe_idOnly = await prisma.recipe_bags.findMany({ select: { recipe_id: true } })
   * 
   */
  findMany<T extends Recipe_bagsFindManyArgs>(args?: Prisma.SelectSubset<T, Recipe_bagsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Recipe_bags.
   * @param {Recipe_bagsCreateArgs} args - Arguments to create a Recipe_bags.
   * @example
   * // Create one Recipe_bags
   * const Recipe_bags = await prisma.recipe_bags.create({
   *   data: {
   *     // ... data to create a Recipe_bags
   *   }
   * })
   * 
   */
  create<T extends Recipe_bagsCreateArgs>(args: Prisma.SelectSubset<T, Recipe_bagsCreateArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Recipe_bags.
   * @param {Recipe_bagsCreateManyArgs} args - Arguments to create many Recipe_bags.
   * @example
   * // Create many Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Recipe_bagsCreateManyArgs>(args?: Prisma.SelectSubset<T, Recipe_bagsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Recipe_bags and returns the data saved in the database.
   * @param {Recipe_bagsCreateManyAndReturnArgs} args - Arguments to create many Recipe_bags.
   * @example
   * // Create many Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Recipe_bags and only return the `recipe_id`
   * const recipe_bagsWithRecipe_idOnly = await prisma.recipe_bags.createManyAndReturn({
   *   select: { recipe_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Recipe_bagsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Recipe_bagsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Recipe_bags.
   * @param {Recipe_bagsDeleteArgs} args - Arguments to delete one Recipe_bags.
   * @example
   * // Delete one Recipe_bags
   * const Recipe_bags = await prisma.recipe_bags.delete({
   *   where: {
   *     // ... filter to delete one Recipe_bags
   *   }
   * })
   * 
   */
  delete<T extends Recipe_bagsDeleteArgs>(args: Prisma.SelectSubset<T, Recipe_bagsDeleteArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Recipe_bags.
   * @param {Recipe_bagsUpdateArgs} args - Arguments to update one Recipe_bags.
   * @example
   * // Update one Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Recipe_bagsUpdateArgs>(args: Prisma.SelectSubset<T, Recipe_bagsUpdateArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Recipe_bags.
   * @param {Recipe_bagsDeleteManyArgs} args - Arguments to filter Recipe_bags to delete.
   * @example
   * // Delete a few Recipe_bags
   * const { count } = await prisma.recipe_bags.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Recipe_bagsDeleteManyArgs>(args?: Prisma.SelectSubset<T, Recipe_bagsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Recipe_bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Recipe_bagsUpdateManyArgs>(args: Prisma.SelectSubset<T, Recipe_bagsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Recipe_bags and returns the data updated in the database.
   * @param {Recipe_bagsUpdateManyAndReturnArgs} args - Arguments to update many Recipe_bags.
   * @example
   * // Update many Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Recipe_bags and only return the `recipe_id`
   * const recipe_bagsWithRecipe_idOnly = await prisma.recipe_bags.updateManyAndReturn({
   *   select: { recipe_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Recipe_bagsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Recipe_bagsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Recipe_bags.
   * @param {Recipe_bagsUpsertArgs} args - Arguments to update or create a Recipe_bags.
   * @example
   * // Update or create a Recipe_bags
   * const recipe_bags = await prisma.recipe_bags.upsert({
   *   create: {
   *     // ... data to create a Recipe_bags
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Recipe_bags we want to update
   *   }
   * })
   */
  upsert<T extends Recipe_bagsUpsertArgs>(args: Prisma.SelectSubset<T, Recipe_bagsUpsertArgs<ExtArgs>>): Prisma.Prisma__Recipe_bagsClient<runtime.Types.Result.GetResult<Prisma.$Recipe_bagsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Recipe_bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsCountArgs} args - Arguments to filter Recipe_bags to count.
   * @example
   * // Count the number of Recipe_bags
   * const count = await prisma.recipe_bags.count({
   *   where: {
   *     // ... the filter for the Recipe_bags we want to count
   *   }
   * })
  **/
  count<T extends Recipe_bagsCountArgs>(
    args?: Prisma.Subset<T, Recipe_bagsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Recipe_bagsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Recipe_bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Recipe_bagsAggregateArgs>(args: Prisma.Subset<T, Recipe_bagsAggregateArgs>): Prisma.PrismaPromise<GetRecipe_bagsAggregateType<T>>

  /**
   * Group by Recipe_bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Recipe_bagsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Recipe_bagsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Recipe_bagsGroupByArgs['orderBy'] }
      : { orderBy?: Recipe_bagsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Recipe_bagsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipe_bagsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Recipe_bags model
 */
readonly fields: Recipe_bagsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Recipe_bags.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Recipe_bagsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bag<T extends Prisma.BagsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BagsDefaultArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  recipe<T extends Prisma.RecipesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RecipesDefaultArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Recipe_bags model
 */
export interface Recipe_bagsFieldRefs {
  readonly recipe_id: Prisma.FieldRef<"Recipe_bags", 'String'>
  readonly bag_id: Prisma.FieldRef<"Recipe_bags", 'String'>
  readonly position: Prisma.FieldRef<"Recipe_bags", 'Int'>
  readonly with_acl: Prisma.FieldRef<"Recipe_bags", 'Boolean'>
  readonly load_modules: Prisma.FieldRef<"Recipe_bags", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Recipe_bags findUnique
 */
export type Recipe_bagsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * Filter, which Recipe_bags to fetch.
   */
  where: Prisma.Recipe_bagsWhereUniqueInput
}

/**
 * Recipe_bags findUniqueOrThrow
 */
export type Recipe_bagsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * Filter, which Recipe_bags to fetch.
   */
  where: Prisma.Recipe_bagsWhereUniqueInput
}

/**
 * Recipe_bags findFirst
 */
export type Recipe_bagsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * Filter, which Recipe_bags to fetch.
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipe_bags to fetch.
   */
  orderBy?: Prisma.Recipe_bagsOrderByWithRelationInput | Prisma.Recipe_bagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Recipe_bags.
   */
  cursor?: Prisma.Recipe_bagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipe_bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipe_bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipe_bags.
   */
  distinct?: Prisma.Recipe_bagsScalarFieldEnum | Prisma.Recipe_bagsScalarFieldEnum[]
}

/**
 * Recipe_bags findFirstOrThrow
 */
export type Recipe_bagsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * Filter, which Recipe_bags to fetch.
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipe_bags to fetch.
   */
  orderBy?: Prisma.Recipe_bagsOrderByWithRelationInput | Prisma.Recipe_bagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Recipe_bags.
   */
  cursor?: Prisma.Recipe_bagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipe_bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipe_bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipe_bags.
   */
  distinct?: Prisma.Recipe_bagsScalarFieldEnum | Prisma.Recipe_bagsScalarFieldEnum[]
}

/**
 * Recipe_bags findMany
 */
export type Recipe_bagsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * Filter, which Recipe_bags to fetch.
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipe_bags to fetch.
   */
  orderBy?: Prisma.Recipe_bagsOrderByWithRelationInput | Prisma.Recipe_bagsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Recipe_bags.
   */
  cursor?: Prisma.Recipe_bagsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipe_bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipe_bags.
   */
  skip?: number
  distinct?: Prisma.Recipe_bagsScalarFieldEnum | Prisma.Recipe_bagsScalarFieldEnum[]
}

/**
 * Recipe_bags create
 */
export type Recipe_bagsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * The data needed to create a Recipe_bags.
   */
  data: Prisma.XOR<Prisma.Recipe_bagsCreateInput, Prisma.Recipe_bagsUncheckedCreateInput>
}

/**
 * Recipe_bags createMany
 */
export type Recipe_bagsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Recipe_bags.
   */
  data: Prisma.Recipe_bagsCreateManyInput | Prisma.Recipe_bagsCreateManyInput[]
}

/**
 * Recipe_bags createManyAndReturn
 */
export type Recipe_bagsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * The data used to create many Recipe_bags.
   */
  data: Prisma.Recipe_bagsCreateManyInput | Prisma.Recipe_bagsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Recipe_bags update
 */
export type Recipe_bagsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * The data needed to update a Recipe_bags.
   */
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateInput, Prisma.Recipe_bagsUncheckedUpdateInput>
  /**
   * Choose, which Recipe_bags to update.
   */
  where: Prisma.Recipe_bagsWhereUniqueInput
}

/**
 * Recipe_bags updateMany
 */
export type Recipe_bagsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Recipe_bags.
   */
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateManyMutationInput, Prisma.Recipe_bagsUncheckedUpdateManyInput>
  /**
   * Filter which Recipe_bags to update
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * Limit how many Recipe_bags to update.
   */
  limit?: number
}

/**
 * Recipe_bags updateManyAndReturn
 */
export type Recipe_bagsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * The data used to update Recipe_bags.
   */
  data: Prisma.XOR<Prisma.Recipe_bagsUpdateManyMutationInput, Prisma.Recipe_bagsUncheckedUpdateManyInput>
  /**
   * Filter which Recipe_bags to update
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * Limit how many Recipe_bags to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Recipe_bags upsert
 */
export type Recipe_bagsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * The filter to search for the Recipe_bags to update in case it exists.
   */
  where: Prisma.Recipe_bagsWhereUniqueInput
  /**
   * In case the Recipe_bags found by the `where` argument doesn't exist, create a new Recipe_bags with this data.
   */
  create: Prisma.XOR<Prisma.Recipe_bagsCreateInput, Prisma.Recipe_bagsUncheckedCreateInput>
  /**
   * In case the Recipe_bags was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Recipe_bagsUpdateInput, Prisma.Recipe_bagsUncheckedUpdateInput>
}

/**
 * Recipe_bags delete
 */
export type Recipe_bagsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
  /**
   * Filter which Recipe_bags to delete.
   */
  where: Prisma.Recipe_bagsWhereUniqueInput
}

/**
 * Recipe_bags deleteMany
 */
export type Recipe_bagsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Recipe_bags to delete
   */
  where?: Prisma.Recipe_bagsWhereInput
  /**
   * Limit how many Recipe_bags to delete.
   */
  limit?: number
}

/**
 * Recipe_bags without action
 */
export type Recipe_bagsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe_bags
   */
  select?: Prisma.Recipe_bagsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe_bags
   */
  omit?: Prisma.Recipe_bagsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Recipe_bagsInclude<ExtArgs> | null
}
