
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecipeAcl` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RecipeAcl
 * 
 */
export type RecipeAclModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipeAclPayload>

export type AggregateRecipeAcl = {
  _count: RecipeAclCountAggregateOutputType | null
  _avg: RecipeAclAvgAggregateOutputType | null
  _sum: RecipeAclSumAggregateOutputType | null
  _min: RecipeAclMinAggregateOutputType | null
  _max: RecipeAclMaxAggregateOutputType | null
}

export type RecipeAclAvgAggregateOutputType = {
  acl_id: number | null
}

export type RecipeAclSumAggregateOutputType = {
  acl_id: number | null
}

export type RecipeAclMinAggregateOutputType = {
  acl_id: number | null
  role_id: string | null
  permission: $Enums.Permission | null
  recipe_id: string | null
}

export type RecipeAclMaxAggregateOutputType = {
  acl_id: number | null
  role_id: string | null
  permission: $Enums.Permission | null
  recipe_id: string | null
}

export type RecipeAclCountAggregateOutputType = {
  acl_id: number
  role_id: number
  permission: number
  recipe_id: number
  _all: number
}


export type RecipeAclAvgAggregateInputType = {
  acl_id?: true
}

export type RecipeAclSumAggregateInputType = {
  acl_id?: true
}

export type RecipeAclMinAggregateInputType = {
  acl_id?: true
  role_id?: true
  permission?: true
  recipe_id?: true
}

export type RecipeAclMaxAggregateInputType = {
  acl_id?: true
  role_id?: true
  permission?: true
  recipe_id?: true
}

export type RecipeAclCountAggregateInputType = {
  acl_id?: true
  role_id?: true
  permission?: true
  recipe_id?: true
  _all?: true
}

export type RecipeAclAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipeAcl to aggregate.
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeAcls to fetch.
   */
  orderBy?: Prisma.RecipeAclOrderByWithRelationInput | Prisma.RecipeAclOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipeAclWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeAcls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeAcls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecipeAcls
  **/
  _count?: true | RecipeAclCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RecipeAclAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RecipeAclSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipeAclMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipeAclMaxAggregateInputType
}

export type GetRecipeAclAggregateType<T extends RecipeAclAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipeAcl]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipeAcl[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipeAcl[P]>
}




export type RecipeAclGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeAclWhereInput
  orderBy?: Prisma.RecipeAclOrderByWithAggregationInput | Prisma.RecipeAclOrderByWithAggregationInput[]
  by: Prisma.RecipeAclScalarFieldEnum[] | Prisma.RecipeAclScalarFieldEnum
  having?: Prisma.RecipeAclScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipeAclCountAggregateInputType | true
  _avg?: RecipeAclAvgAggregateInputType
  _sum?: RecipeAclSumAggregateInputType
  _min?: RecipeAclMinAggregateInputType
  _max?: RecipeAclMaxAggregateInputType
}

export type RecipeAclGroupByOutputType = {
  acl_id: number
  role_id: string
  permission: $Enums.Permission
  recipe_id: string
  _count: RecipeAclCountAggregateOutputType | null
  _avg: RecipeAclAvgAggregateOutputType | null
  _sum: RecipeAclSumAggregateOutputType | null
  _min: RecipeAclMinAggregateOutputType | null
  _max: RecipeAclMaxAggregateOutputType | null
}

type GetRecipeAclGroupByPayload<T extends RecipeAclGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipeAclGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipeAclGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipeAclGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipeAclGroupByOutputType[P]>
      }
    >
  >



export type RecipeAclWhereInput = {
  AND?: Prisma.RecipeAclWhereInput | Prisma.RecipeAclWhereInput[]
  OR?: Prisma.RecipeAclWhereInput[]
  NOT?: Prisma.RecipeAclWhereInput | Prisma.RecipeAclWhereInput[]
  acl_id?: Prisma.IntFilter<"RecipeAcl"> | number
  role_id?: Prisma.StringFilter<"RecipeAcl"> | string
  permission?: Prisma.EnumPermissionFilter<"RecipeAcl"> | $Enums.Permission
  recipe_id?: Prisma.StringFilter<"RecipeAcl"> | string
  recipe?: Prisma.XOR<Prisma.RecipesScalarRelationFilter, Prisma.RecipesWhereInput>
}

export type RecipeAclOrderByWithRelationInput = {
  acl_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
  recipe?: Prisma.RecipesOrderByWithRelationInput
}

export type RecipeAclWhereUniqueInput = Prisma.AtLeast<{
  acl_id?: number
  AND?: Prisma.RecipeAclWhereInput | Prisma.RecipeAclWhereInput[]
  OR?: Prisma.RecipeAclWhereInput[]
  NOT?: Prisma.RecipeAclWhereInput | Prisma.RecipeAclWhereInput[]
  role_id?: Prisma.StringFilter<"RecipeAcl"> | string
  permission?: Prisma.EnumPermissionFilter<"RecipeAcl"> | $Enums.Permission
  recipe_id?: Prisma.StringFilter<"RecipeAcl"> | string
  recipe?: Prisma.XOR<Prisma.RecipesScalarRelationFilter, Prisma.RecipesWhereInput>
}, "acl_id">

export type RecipeAclOrderByWithAggregationInput = {
  acl_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
  _count?: Prisma.RecipeAclCountOrderByAggregateInput
  _avg?: Prisma.RecipeAclAvgOrderByAggregateInput
  _max?: Prisma.RecipeAclMaxOrderByAggregateInput
  _min?: Prisma.RecipeAclMinOrderByAggregateInput
  _sum?: Prisma.RecipeAclSumOrderByAggregateInput
}

export type RecipeAclScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipeAclScalarWhereWithAggregatesInput | Prisma.RecipeAclScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipeAclScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipeAclScalarWhereWithAggregatesInput | Prisma.RecipeAclScalarWhereWithAggregatesInput[]
  acl_id?: Prisma.IntWithAggregatesFilter<"RecipeAcl"> | number
  role_id?: Prisma.StringWithAggregatesFilter<"RecipeAcl"> | string
  permission?: Prisma.EnumPermissionWithAggregatesFilter<"RecipeAcl"> | $Enums.Permission
  recipe_id?: Prisma.StringWithAggregatesFilter<"RecipeAcl"> | string
}

export type RecipeAclCreateInput = {
  role_id: string
  permission: $Enums.Permission
  recipe: Prisma.RecipesCreateNestedOneWithoutAclInput
}

export type RecipeAclUncheckedCreateInput = {
  acl_id?: number
  role_id: string
  permission: $Enums.Permission
  recipe_id: string
}

export type RecipeAclUpdateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
  recipe?: Prisma.RecipesUpdateOneRequiredWithoutAclNestedInput
}

export type RecipeAclUncheckedUpdateInput = {
  acl_id?: Prisma.IntFieldUpdateOperationsInput | number
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipeAclCreateManyInput = {
  acl_id?: number
  role_id: string
  permission: $Enums.Permission
  recipe_id: string
}

export type RecipeAclUpdateManyMutationInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
}

export type RecipeAclUncheckedUpdateManyInput = {
  acl_id?: Prisma.IntFieldUpdateOperationsInput | number
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipeAclListRelationFilter = {
  every?: Prisma.RecipeAclWhereInput
  some?: Prisma.RecipeAclWhereInput
  none?: Prisma.RecipeAclWhereInput
}

export type RecipeAclOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecipeAclCountOrderByAggregateInput = {
  acl_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
}

export type RecipeAclAvgOrderByAggregateInput = {
  acl_id?: Prisma.SortOrder
}

export type RecipeAclMaxOrderByAggregateInput = {
  acl_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
}

export type RecipeAclMinOrderByAggregateInput = {
  acl_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
}

export type RecipeAclSumOrderByAggregateInput = {
  acl_id?: Prisma.SortOrder
}

export type RecipeAclCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipeAclCreateWithoutRecipeInput, Prisma.RecipeAclUncheckedCreateWithoutRecipeInput> | Prisma.RecipeAclCreateWithoutRecipeInput[] | Prisma.RecipeAclUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeAclCreateOrConnectWithoutRecipeInput | Prisma.RecipeAclCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipeAclCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
}

export type RecipeAclUncheckedCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipeAclCreateWithoutRecipeInput, Prisma.RecipeAclUncheckedCreateWithoutRecipeInput> | Prisma.RecipeAclCreateWithoutRecipeInput[] | Prisma.RecipeAclUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeAclCreateOrConnectWithoutRecipeInput | Prisma.RecipeAclCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipeAclCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
}

export type RecipeAclUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeAclCreateWithoutRecipeInput, Prisma.RecipeAclUncheckedCreateWithoutRecipeInput> | Prisma.RecipeAclCreateWithoutRecipeInput[] | Prisma.RecipeAclUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeAclCreateOrConnectWithoutRecipeInput | Prisma.RecipeAclCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipeAclUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipeAclUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipeAclCreateManyRecipeInputEnvelope
  set?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  disconnect?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  delete?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  connect?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  update?: Prisma.RecipeAclUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipeAclUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipeAclUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipeAclUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipeAclScalarWhereInput | Prisma.RecipeAclScalarWhereInput[]
}

export type RecipeAclUncheckedUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeAclCreateWithoutRecipeInput, Prisma.RecipeAclUncheckedCreateWithoutRecipeInput> | Prisma.RecipeAclCreateWithoutRecipeInput[] | Prisma.RecipeAclUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipeAclCreateOrConnectWithoutRecipeInput | Prisma.RecipeAclCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipeAclUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipeAclUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipeAclCreateManyRecipeInputEnvelope
  set?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  disconnect?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  delete?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  connect?: Prisma.RecipeAclWhereUniqueInput | Prisma.RecipeAclWhereUniqueInput[]
  update?: Prisma.RecipeAclUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipeAclUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipeAclUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipeAclUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipeAclScalarWhereInput | Prisma.RecipeAclScalarWhereInput[]
}

export type EnumPermissionFieldUpdateOperationsInput = {
  set?: $Enums.Permission
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type RecipeAclCreateWithoutRecipeInput = {
  role_id: string
  permission: $Enums.Permission
}

export type RecipeAclUncheckedCreateWithoutRecipeInput = {
  acl_id?: number
  role_id: string
  permission: $Enums.Permission
}

export type RecipeAclCreateOrConnectWithoutRecipeInput = {
  where: Prisma.RecipeAclWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipeAclCreateWithoutRecipeInput, Prisma.RecipeAclUncheckedCreateWithoutRecipeInput>
}

export type RecipeAclCreateManyRecipeInputEnvelope = {
  data: Prisma.RecipeAclCreateManyRecipeInput | Prisma.RecipeAclCreateManyRecipeInput[]
}

export type RecipeAclUpsertWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipeAclWhereUniqueInput
  update: Prisma.XOR<Prisma.RecipeAclUpdateWithoutRecipeInput, Prisma.RecipeAclUncheckedUpdateWithoutRecipeInput>
  create: Prisma.XOR<Prisma.RecipeAclCreateWithoutRecipeInput, Prisma.RecipeAclUncheckedCreateWithoutRecipeInput>
}

export type RecipeAclUpdateWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipeAclWhereUniqueInput
  data: Prisma.XOR<Prisma.RecipeAclUpdateWithoutRecipeInput, Prisma.RecipeAclUncheckedUpdateWithoutRecipeInput>
}

export type RecipeAclUpdateManyWithWhereWithoutRecipeInput = {
  where: Prisma.RecipeAclScalarWhereInput
  data: Prisma.XOR<Prisma.RecipeAclUpdateManyMutationInput, Prisma.RecipeAclUncheckedUpdateManyWithoutRecipeInput>
}

export type RecipeAclScalarWhereInput = {
  AND?: Prisma.RecipeAclScalarWhereInput | Prisma.RecipeAclScalarWhereInput[]
  OR?: Prisma.RecipeAclScalarWhereInput[]
  NOT?: Prisma.RecipeAclScalarWhereInput | Prisma.RecipeAclScalarWhereInput[]
  acl_id?: Prisma.IntFilter<"RecipeAcl"> | number
  role_id?: Prisma.StringFilter<"RecipeAcl"> | string
  permission?: Prisma.EnumPermissionFilter<"RecipeAcl"> | $Enums.Permission
  recipe_id?: Prisma.StringFilter<"RecipeAcl"> | string
}

export type RecipeAclCreateManyRecipeInput = {
  acl_id?: number
  role_id: string
  permission: $Enums.Permission
}

export type RecipeAclUpdateWithoutRecipeInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
}

export type RecipeAclUncheckedUpdateWithoutRecipeInput = {
  acl_id?: Prisma.IntFieldUpdateOperationsInput | number
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
}

export type RecipeAclUncheckedUpdateManyWithoutRecipeInput = {
  acl_id?: Prisma.IntFieldUpdateOperationsInput | number
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionFieldUpdateOperationsInput | $Enums.Permission
}



export type RecipeAclSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  acl_id?: boolean
  role_id?: boolean
  permission?: boolean
  recipe_id?: boolean
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeAcl"]>

export type RecipeAclSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  acl_id?: boolean
  role_id?: boolean
  permission?: boolean
  recipe_id?: boolean
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeAcl"]>

export type RecipeAclSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  acl_id?: boolean
  role_id?: boolean
  permission?: boolean
  recipe_id?: boolean
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipeAcl"]>

export type RecipeAclSelectScalar = {
  acl_id?: boolean
  role_id?: boolean
  permission?: boolean
  recipe_id?: boolean
}

export type RecipeAclOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"acl_id" | "role_id" | "permission" | "recipe_id", ExtArgs["result"]["recipeAcl"]>
export type RecipeAclInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}
export type RecipeAclIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}
export type RecipeAclIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipesDefaultArgs<ExtArgs>
}

export type $RecipeAclPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecipeAcl"
  objects: {
    recipe: Prisma.$RecipesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    acl_id: number
    role_id: string
    permission: $Enums.Permission
    recipe_id: string
  }, ExtArgs["result"]["recipeAcl"]>
  composites: {}
}

export type RecipeAclGetPayload<S extends boolean | null | undefined | RecipeAclDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload, S>

export type RecipeAclCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipeAclFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipeAclCountAggregateInputType | true
  }

export interface RecipeAclDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecipeAcl'], meta: { name: 'RecipeAcl' } }
  /**
   * Find zero or one RecipeAcl that matches the filter.
   * @param {RecipeAclFindUniqueArgs} args - Arguments to find a RecipeAcl
   * @example
   * // Get one RecipeAcl
   * const recipeAcl = await prisma.recipeAcl.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipeAclFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipeAclFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecipeAcl that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipeAclFindUniqueOrThrowArgs} args - Arguments to find a RecipeAcl
   * @example
   * // Get one RecipeAcl
   * const recipeAcl = await prisma.recipeAcl.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipeAclFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipeAclFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipeAcl that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclFindFirstArgs} args - Arguments to find a RecipeAcl
   * @example
   * // Get one RecipeAcl
   * const recipeAcl = await prisma.recipeAcl.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipeAclFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipeAclFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipeAcl that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclFindFirstOrThrowArgs} args - Arguments to find a RecipeAcl
   * @example
   * // Get one RecipeAcl
   * const recipeAcl = await prisma.recipeAcl.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipeAclFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipeAclFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecipeAcls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecipeAcls
   * const recipeAcls = await prisma.recipeAcl.findMany()
   * 
   * // Get first 10 RecipeAcls
   * const recipeAcls = await prisma.recipeAcl.findMany({ take: 10 })
   * 
   * // Only select the `acl_id`
   * const recipeAclWithAcl_idOnly = await prisma.recipeAcl.findMany({ select: { acl_id: true } })
   * 
   */
  findMany<T extends RecipeAclFindManyArgs>(args?: Prisma.SelectSubset<T, RecipeAclFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecipeAcl.
   * @param {RecipeAclCreateArgs} args - Arguments to create a RecipeAcl.
   * @example
   * // Create one RecipeAcl
   * const RecipeAcl = await prisma.recipeAcl.create({
   *   data: {
   *     // ... data to create a RecipeAcl
   *   }
   * })
   * 
   */
  create<T extends RecipeAclCreateArgs>(args: Prisma.SelectSubset<T, RecipeAclCreateArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecipeAcls.
   * @param {RecipeAclCreateManyArgs} args - Arguments to create many RecipeAcls.
   * @example
   * // Create many RecipeAcls
   * const recipeAcl = await prisma.recipeAcl.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipeAclCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipeAclCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecipeAcls and returns the data saved in the database.
   * @param {RecipeAclCreateManyAndReturnArgs} args - Arguments to create many RecipeAcls.
   * @example
   * // Create many RecipeAcls
   * const recipeAcl = await prisma.recipeAcl.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecipeAcls and only return the `acl_id`
   * const recipeAclWithAcl_idOnly = await prisma.recipeAcl.createManyAndReturn({
   *   select: { acl_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipeAclCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipeAclCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecipeAcl.
   * @param {RecipeAclDeleteArgs} args - Arguments to delete one RecipeAcl.
   * @example
   * // Delete one RecipeAcl
   * const RecipeAcl = await prisma.recipeAcl.delete({
   *   where: {
   *     // ... filter to delete one RecipeAcl
   *   }
   * })
   * 
   */
  delete<T extends RecipeAclDeleteArgs>(args: Prisma.SelectSubset<T, RecipeAclDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecipeAcl.
   * @param {RecipeAclUpdateArgs} args - Arguments to update one RecipeAcl.
   * @example
   * // Update one RecipeAcl
   * const recipeAcl = await prisma.recipeAcl.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipeAclUpdateArgs>(args: Prisma.SelectSubset<T, RecipeAclUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecipeAcls.
   * @param {RecipeAclDeleteManyArgs} args - Arguments to filter RecipeAcls to delete.
   * @example
   * // Delete a few RecipeAcls
   * const { count } = await prisma.recipeAcl.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipeAclDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipeAclDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipeAcls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecipeAcls
   * const recipeAcl = await prisma.recipeAcl.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipeAclUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipeAclUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipeAcls and returns the data updated in the database.
   * @param {RecipeAclUpdateManyAndReturnArgs} args - Arguments to update many RecipeAcls.
   * @example
   * // Update many RecipeAcls
   * const recipeAcl = await prisma.recipeAcl.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecipeAcls and only return the `acl_id`
   * const recipeAclWithAcl_idOnly = await prisma.recipeAcl.updateManyAndReturn({
   *   select: { acl_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipeAclUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipeAclUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecipeAcl.
   * @param {RecipeAclUpsertArgs} args - Arguments to update or create a RecipeAcl.
   * @example
   * // Update or create a RecipeAcl
   * const recipeAcl = await prisma.recipeAcl.upsert({
   *   create: {
   *     // ... data to create a RecipeAcl
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecipeAcl we want to update
   *   }
   * })
   */
  upsert<T extends RecipeAclUpsertArgs>(args: Prisma.SelectSubset<T, RecipeAclUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipeAclClient<runtime.Types.Result.GetResult<Prisma.$RecipeAclPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecipeAcls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclCountArgs} args - Arguments to filter RecipeAcls to count.
   * @example
   * // Count the number of RecipeAcls
   * const count = await prisma.recipeAcl.count({
   *   where: {
   *     // ... the filter for the RecipeAcls we want to count
   *   }
   * })
  **/
  count<T extends RecipeAclCountArgs>(
    args?: Prisma.Subset<T, RecipeAclCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipeAclCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecipeAcl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipeAclAggregateArgs>(args: Prisma.Subset<T, RecipeAclAggregateArgs>): Prisma.PrismaPromise<GetRecipeAclAggregateType<T>>

  /**
   * Group by RecipeAcl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAclGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipeAclGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipeAclGroupByArgs['orderBy'] }
      : { orderBy?: RecipeAclGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipeAclGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipeAclGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecipeAcl model
 */
readonly fields: RecipeAclFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecipeAcl.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipeAclClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe<T extends Prisma.RecipesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RecipesDefaultArgs<ExtArgs>>): Prisma.Prisma__RecipesClient<runtime.Types.Result.GetResult<Prisma.$RecipesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecipeAcl model
 */
export interface RecipeAclFieldRefs {
  readonly acl_id: Prisma.FieldRef<"RecipeAcl", 'Int'>
  readonly role_id: Prisma.FieldRef<"RecipeAcl", 'String'>
  readonly permission: Prisma.FieldRef<"RecipeAcl", 'Permission'>
  readonly recipe_id: Prisma.FieldRef<"RecipeAcl", 'String'>
}
    

// Custom InputTypes
/**
 * RecipeAcl findUnique
 */
export type RecipeAclFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * Filter, which RecipeAcl to fetch.
   */
  where: Prisma.RecipeAclWhereUniqueInput
}

/**
 * RecipeAcl findUniqueOrThrow
 */
export type RecipeAclFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * Filter, which RecipeAcl to fetch.
   */
  where: Prisma.RecipeAclWhereUniqueInput
}

/**
 * RecipeAcl findFirst
 */
export type RecipeAclFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * Filter, which RecipeAcl to fetch.
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeAcls to fetch.
   */
  orderBy?: Prisma.RecipeAclOrderByWithRelationInput | Prisma.RecipeAclOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipeAcls.
   */
  cursor?: Prisma.RecipeAclWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeAcls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeAcls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeAcls.
   */
  distinct?: Prisma.RecipeAclScalarFieldEnum | Prisma.RecipeAclScalarFieldEnum[]
}

/**
 * RecipeAcl findFirstOrThrow
 */
export type RecipeAclFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * Filter, which RecipeAcl to fetch.
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeAcls to fetch.
   */
  orderBy?: Prisma.RecipeAclOrderByWithRelationInput | Prisma.RecipeAclOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipeAcls.
   */
  cursor?: Prisma.RecipeAclWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeAcls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeAcls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipeAcls.
   */
  distinct?: Prisma.RecipeAclScalarFieldEnum | Prisma.RecipeAclScalarFieldEnum[]
}

/**
 * RecipeAcl findMany
 */
export type RecipeAclFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * Filter, which RecipeAcls to fetch.
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipeAcls to fetch.
   */
  orderBy?: Prisma.RecipeAclOrderByWithRelationInput | Prisma.RecipeAclOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecipeAcls.
   */
  cursor?: Prisma.RecipeAclWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipeAcls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipeAcls.
   */
  skip?: number
  distinct?: Prisma.RecipeAclScalarFieldEnum | Prisma.RecipeAclScalarFieldEnum[]
}

/**
 * RecipeAcl create
 */
export type RecipeAclCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * The data needed to create a RecipeAcl.
   */
  data: Prisma.XOR<Prisma.RecipeAclCreateInput, Prisma.RecipeAclUncheckedCreateInput>
}

/**
 * RecipeAcl createMany
 */
export type RecipeAclCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecipeAcls.
   */
  data: Prisma.RecipeAclCreateManyInput | Prisma.RecipeAclCreateManyInput[]
}

/**
 * RecipeAcl createManyAndReturn
 */
export type RecipeAclCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * The data used to create many RecipeAcls.
   */
  data: Prisma.RecipeAclCreateManyInput | Prisma.RecipeAclCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecipeAcl update
 */
export type RecipeAclUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * The data needed to update a RecipeAcl.
   */
  data: Prisma.XOR<Prisma.RecipeAclUpdateInput, Prisma.RecipeAclUncheckedUpdateInput>
  /**
   * Choose, which RecipeAcl to update.
   */
  where: Prisma.RecipeAclWhereUniqueInput
}

/**
 * RecipeAcl updateMany
 */
export type RecipeAclUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecipeAcls.
   */
  data: Prisma.XOR<Prisma.RecipeAclUpdateManyMutationInput, Prisma.RecipeAclUncheckedUpdateManyInput>
  /**
   * Filter which RecipeAcls to update
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * Limit how many RecipeAcls to update.
   */
  limit?: number
}

/**
 * RecipeAcl updateManyAndReturn
 */
export type RecipeAclUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * The data used to update RecipeAcls.
   */
  data: Prisma.XOR<Prisma.RecipeAclUpdateManyMutationInput, Prisma.RecipeAclUncheckedUpdateManyInput>
  /**
   * Filter which RecipeAcls to update
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * Limit how many RecipeAcls to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecipeAcl upsert
 */
export type RecipeAclUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * The filter to search for the RecipeAcl to update in case it exists.
   */
  where: Prisma.RecipeAclWhereUniqueInput
  /**
   * In case the RecipeAcl found by the `where` argument doesn't exist, create a new RecipeAcl with this data.
   */
  create: Prisma.XOR<Prisma.RecipeAclCreateInput, Prisma.RecipeAclUncheckedCreateInput>
  /**
   * In case the RecipeAcl was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipeAclUpdateInput, Prisma.RecipeAclUncheckedUpdateInput>
}

/**
 * RecipeAcl delete
 */
export type RecipeAclDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
  /**
   * Filter which RecipeAcl to delete.
   */
  where: Prisma.RecipeAclWhereUniqueInput
}

/**
 * RecipeAcl deleteMany
 */
export type RecipeAclDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipeAcls to delete
   */
  where?: Prisma.RecipeAclWhereInput
  /**
   * Limit how many RecipeAcls to delete.
   */
  limit?: number
}

/**
 * RecipeAcl without action
 */
export type RecipeAclDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeAcl
   */
  select?: Prisma.RecipeAclSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeAcl
   */
  omit?: Prisma.RecipeAclOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeAclInclude<ExtArgs> | null
}
