
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tiddlers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Tiddlers
 * 
 */
export type TiddlersModel = runtime.Types.Result.DefaultSelection<Prisma.$TiddlersPayload>

export type AggregateTiddlers = {
  _count: TiddlersCountAggregateOutputType | null
  _min: TiddlersMinAggregateOutputType | null
  _max: TiddlersMaxAggregateOutputType | null
}

export type TiddlersMinAggregateOutputType = {
  revision_id: string | null
  bag_id: string | null
  title: string | null
  is_deleted: boolean | null
  attachment_hash: string | null
}

export type TiddlersMaxAggregateOutputType = {
  revision_id: string | null
  bag_id: string | null
  title: string | null
  is_deleted: boolean | null
  attachment_hash: string | null
}

export type TiddlersCountAggregateOutputType = {
  revision_id: number
  bag_id: number
  title: number
  is_deleted: number
  attachment_hash: number
  _all: number
}


export type TiddlersMinAggregateInputType = {
  revision_id?: true
  bag_id?: true
  title?: true
  is_deleted?: true
  attachment_hash?: true
}

export type TiddlersMaxAggregateInputType = {
  revision_id?: true
  bag_id?: true
  title?: true
  is_deleted?: true
  attachment_hash?: true
}

export type TiddlersCountAggregateInputType = {
  revision_id?: true
  bag_id?: true
  title?: true
  is_deleted?: true
  attachment_hash?: true
  _all?: true
}

export type TiddlersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tiddlers to aggregate.
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlersOrderByWithRelationInput | Prisma.TiddlersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TiddlersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tiddlers
  **/
  _count?: true | TiddlersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TiddlersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TiddlersMaxAggregateInputType
}

export type GetTiddlersAggregateType<T extends TiddlersAggregateArgs> = {
      [P in keyof T & keyof AggregateTiddlers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTiddlers[P]>
    : Prisma.GetScalarType<T[P], AggregateTiddlers[P]>
}




export type TiddlersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiddlersWhereInput
  orderBy?: Prisma.TiddlersOrderByWithAggregationInput | Prisma.TiddlersOrderByWithAggregationInput[]
  by: Prisma.TiddlersScalarFieldEnum[] | Prisma.TiddlersScalarFieldEnum
  having?: Prisma.TiddlersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TiddlersCountAggregateInputType | true
  _min?: TiddlersMinAggregateInputType
  _max?: TiddlersMaxAggregateInputType
}

export type TiddlersGroupByOutputType = {
  revision_id: string
  bag_id: string
  title: string
  is_deleted: boolean
  attachment_hash: string | null
  _count: TiddlersCountAggregateOutputType | null
  _min: TiddlersMinAggregateOutputType | null
  _max: TiddlersMaxAggregateOutputType | null
}

type GetTiddlersGroupByPayload<T extends TiddlersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TiddlersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TiddlersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TiddlersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TiddlersGroupByOutputType[P]>
      }
    >
  >



export type TiddlersWhereInput = {
  AND?: Prisma.TiddlersWhereInput | Prisma.TiddlersWhereInput[]
  OR?: Prisma.TiddlersWhereInput[]
  NOT?: Prisma.TiddlersWhereInput | Prisma.TiddlersWhereInput[]
  revision_id?: Prisma.StringFilter<"Tiddlers"> | string
  bag_id?: Prisma.StringFilter<"Tiddlers"> | string
  title?: Prisma.StringFilter<"Tiddlers"> | string
  is_deleted?: Prisma.BoolFilter<"Tiddlers"> | boolean
  attachment_hash?: Prisma.StringNullableFilter<"Tiddlers"> | string | null
  fields?: Prisma.FieldsListRelationFilter
  bag?: Prisma.XOR<Prisma.BagsScalarRelationFilter, Prisma.BagsWhereInput>
}

export type TiddlersOrderByWithRelationInput = {
  revision_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  attachment_hash?: Prisma.SortOrderInput | Prisma.SortOrder
  fields?: Prisma.FieldsOrderByRelationAggregateInput
  bag?: Prisma.BagsOrderByWithRelationInput
}

export type TiddlersWhereUniqueInput = Prisma.AtLeast<{
  revision_id?: string
  bag_id_title?: Prisma.TiddlersBag_idTitleCompoundUniqueInput
  AND?: Prisma.TiddlersWhereInput | Prisma.TiddlersWhereInput[]
  OR?: Prisma.TiddlersWhereInput[]
  NOT?: Prisma.TiddlersWhereInput | Prisma.TiddlersWhereInput[]
  bag_id?: Prisma.StringFilter<"Tiddlers"> | string
  title?: Prisma.StringFilter<"Tiddlers"> | string
  is_deleted?: Prisma.BoolFilter<"Tiddlers"> | boolean
  attachment_hash?: Prisma.StringNullableFilter<"Tiddlers"> | string | null
  fields?: Prisma.FieldsListRelationFilter
  bag?: Prisma.XOR<Prisma.BagsScalarRelationFilter, Prisma.BagsWhereInput>
}, "revision_id" | "bag_id_title">

export type TiddlersOrderByWithAggregationInput = {
  revision_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  attachment_hash?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TiddlersCountOrderByAggregateInput
  _max?: Prisma.TiddlersMaxOrderByAggregateInput
  _min?: Prisma.TiddlersMinOrderByAggregateInput
}

export type TiddlersScalarWhereWithAggregatesInput = {
  AND?: Prisma.TiddlersScalarWhereWithAggregatesInput | Prisma.TiddlersScalarWhereWithAggregatesInput[]
  OR?: Prisma.TiddlersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TiddlersScalarWhereWithAggregatesInput | Prisma.TiddlersScalarWhereWithAggregatesInput[]
  revision_id?: Prisma.StringWithAggregatesFilter<"Tiddlers"> | string
  bag_id?: Prisma.StringWithAggregatesFilter<"Tiddlers"> | string
  title?: Prisma.StringWithAggregatesFilter<"Tiddlers"> | string
  is_deleted?: Prisma.BoolWithAggregatesFilter<"Tiddlers"> | boolean
  attachment_hash?: Prisma.StringNullableWithAggregatesFilter<"Tiddlers"> | string | null
}

export type TiddlersCreateInput = {
  revision_id?: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
  fields?: Prisma.FieldsCreateNestedManyWithoutTiddlerInput
  bag: Prisma.BagsCreateNestedOneWithoutTiddlersInput
}

export type TiddlersUncheckedCreateInput = {
  revision_id?: string
  bag_id: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
  fields?: Prisma.FieldsUncheckedCreateNestedManyWithoutTiddlerInput
}

export type TiddlersUpdateInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fields?: Prisma.FieldsUpdateManyWithoutTiddlerNestedInput
  bag?: Prisma.BagsUpdateOneRequiredWithoutTiddlersNestedInput
}

export type TiddlersUncheckedUpdateInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fields?: Prisma.FieldsUncheckedUpdateManyWithoutTiddlerNestedInput
}

export type TiddlersCreateManyInput = {
  revision_id?: string
  bag_id: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
}

export type TiddlersUpdateManyMutationInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TiddlersUncheckedUpdateManyInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TiddlersListRelationFilter = {
  every?: Prisma.TiddlersWhereInput
  some?: Prisma.TiddlersWhereInput
  none?: Prisma.TiddlersWhereInput
}

export type TiddlersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TiddlersBag_idTitleCompoundUniqueInput = {
  bag_id: string
  title: string
}

export type TiddlersCountOrderByAggregateInput = {
  revision_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  attachment_hash?: Prisma.SortOrder
}

export type TiddlersMaxOrderByAggregateInput = {
  revision_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  attachment_hash?: Prisma.SortOrder
}

export type TiddlersMinOrderByAggregateInput = {
  revision_id?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  is_deleted?: Prisma.SortOrder
  attachment_hash?: Prisma.SortOrder
}

export type TiddlersScalarRelationFilter = {
  is?: Prisma.TiddlersWhereInput
  isNot?: Prisma.TiddlersWhereInput
}

export type TiddlersCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.TiddlersCreateWithoutBagInput, Prisma.TiddlersUncheckedCreateWithoutBagInput> | Prisma.TiddlersCreateWithoutBagInput[] | Prisma.TiddlersUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlersCreateOrConnectWithoutBagInput | Prisma.TiddlersCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.TiddlersCreateManyBagInputEnvelope
  connect?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
}

export type TiddlersUncheckedCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.TiddlersCreateWithoutBagInput, Prisma.TiddlersUncheckedCreateWithoutBagInput> | Prisma.TiddlersCreateWithoutBagInput[] | Prisma.TiddlersUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlersCreateOrConnectWithoutBagInput | Prisma.TiddlersCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.TiddlersCreateManyBagInputEnvelope
  connect?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
}

export type TiddlersUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlersCreateWithoutBagInput, Prisma.TiddlersUncheckedCreateWithoutBagInput> | Prisma.TiddlersCreateWithoutBagInput[] | Prisma.TiddlersUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlersCreateOrConnectWithoutBagInput | Prisma.TiddlersCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.TiddlersUpsertWithWhereUniqueWithoutBagInput | Prisma.TiddlersUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.TiddlersCreateManyBagInputEnvelope
  set?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  disconnect?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  delete?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  connect?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  update?: Prisma.TiddlersUpdateWithWhereUniqueWithoutBagInput | Prisma.TiddlersUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.TiddlersUpdateManyWithWhereWithoutBagInput | Prisma.TiddlersUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.TiddlersScalarWhereInput | Prisma.TiddlersScalarWhereInput[]
}

export type TiddlersUncheckedUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlersCreateWithoutBagInput, Prisma.TiddlersUncheckedCreateWithoutBagInput> | Prisma.TiddlersCreateWithoutBagInput[] | Prisma.TiddlersUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlersCreateOrConnectWithoutBagInput | Prisma.TiddlersCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.TiddlersUpsertWithWhereUniqueWithoutBagInput | Prisma.TiddlersUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.TiddlersCreateManyBagInputEnvelope
  set?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  disconnect?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  delete?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  connect?: Prisma.TiddlersWhereUniqueInput | Prisma.TiddlersWhereUniqueInput[]
  update?: Prisma.TiddlersUpdateWithWhereUniqueWithoutBagInput | Prisma.TiddlersUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.TiddlersUpdateManyWithWhereWithoutBagInput | Prisma.TiddlersUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.TiddlersScalarWhereInput | Prisma.TiddlersScalarWhereInput[]
}

export type TiddlersCreateNestedOneWithoutFieldsInput = {
  create?: Prisma.XOR<Prisma.TiddlersCreateWithoutFieldsInput, Prisma.TiddlersUncheckedCreateWithoutFieldsInput>
  connectOrCreate?: Prisma.TiddlersCreateOrConnectWithoutFieldsInput
  connect?: Prisma.TiddlersWhereUniqueInput
}

export type TiddlersUpdateOneRequiredWithoutFieldsNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlersCreateWithoutFieldsInput, Prisma.TiddlersUncheckedCreateWithoutFieldsInput>
  connectOrCreate?: Prisma.TiddlersCreateOrConnectWithoutFieldsInput
  upsert?: Prisma.TiddlersUpsertWithoutFieldsInput
  connect?: Prisma.TiddlersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TiddlersUpdateToOneWithWhereWithoutFieldsInput, Prisma.TiddlersUpdateWithoutFieldsInput>, Prisma.TiddlersUncheckedUpdateWithoutFieldsInput>
}

export type TiddlersCreateWithoutBagInput = {
  revision_id?: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
  fields?: Prisma.FieldsCreateNestedManyWithoutTiddlerInput
}

export type TiddlersUncheckedCreateWithoutBagInput = {
  revision_id?: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
  fields?: Prisma.FieldsUncheckedCreateNestedManyWithoutTiddlerInput
}

export type TiddlersCreateOrConnectWithoutBagInput = {
  where: Prisma.TiddlersWhereUniqueInput
  create: Prisma.XOR<Prisma.TiddlersCreateWithoutBagInput, Prisma.TiddlersUncheckedCreateWithoutBagInput>
}

export type TiddlersCreateManyBagInputEnvelope = {
  data: Prisma.TiddlersCreateManyBagInput | Prisma.TiddlersCreateManyBagInput[]
}

export type TiddlersUpsertWithWhereUniqueWithoutBagInput = {
  where: Prisma.TiddlersWhereUniqueInput
  update: Prisma.XOR<Prisma.TiddlersUpdateWithoutBagInput, Prisma.TiddlersUncheckedUpdateWithoutBagInput>
  create: Prisma.XOR<Prisma.TiddlersCreateWithoutBagInput, Prisma.TiddlersUncheckedCreateWithoutBagInput>
}

export type TiddlersUpdateWithWhereUniqueWithoutBagInput = {
  where: Prisma.TiddlersWhereUniqueInput
  data: Prisma.XOR<Prisma.TiddlersUpdateWithoutBagInput, Prisma.TiddlersUncheckedUpdateWithoutBagInput>
}

export type TiddlersUpdateManyWithWhereWithoutBagInput = {
  where: Prisma.TiddlersScalarWhereInput
  data: Prisma.XOR<Prisma.TiddlersUpdateManyMutationInput, Prisma.TiddlersUncheckedUpdateManyWithoutBagInput>
}

export type TiddlersScalarWhereInput = {
  AND?: Prisma.TiddlersScalarWhereInput | Prisma.TiddlersScalarWhereInput[]
  OR?: Prisma.TiddlersScalarWhereInput[]
  NOT?: Prisma.TiddlersScalarWhereInput | Prisma.TiddlersScalarWhereInput[]
  revision_id?: Prisma.StringFilter<"Tiddlers"> | string
  bag_id?: Prisma.StringFilter<"Tiddlers"> | string
  title?: Prisma.StringFilter<"Tiddlers"> | string
  is_deleted?: Prisma.BoolFilter<"Tiddlers"> | boolean
  attachment_hash?: Prisma.StringNullableFilter<"Tiddlers"> | string | null
}

export type TiddlersCreateWithoutFieldsInput = {
  revision_id?: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
  bag: Prisma.BagsCreateNestedOneWithoutTiddlersInput
}

export type TiddlersUncheckedCreateWithoutFieldsInput = {
  revision_id?: string
  bag_id: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
}

export type TiddlersCreateOrConnectWithoutFieldsInput = {
  where: Prisma.TiddlersWhereUniqueInput
  create: Prisma.XOR<Prisma.TiddlersCreateWithoutFieldsInput, Prisma.TiddlersUncheckedCreateWithoutFieldsInput>
}

export type TiddlersUpsertWithoutFieldsInput = {
  update: Prisma.XOR<Prisma.TiddlersUpdateWithoutFieldsInput, Prisma.TiddlersUncheckedUpdateWithoutFieldsInput>
  create: Prisma.XOR<Prisma.TiddlersCreateWithoutFieldsInput, Prisma.TiddlersUncheckedCreateWithoutFieldsInput>
  where?: Prisma.TiddlersWhereInput
}

export type TiddlersUpdateToOneWithWhereWithoutFieldsInput = {
  where?: Prisma.TiddlersWhereInput
  data: Prisma.XOR<Prisma.TiddlersUpdateWithoutFieldsInput, Prisma.TiddlersUncheckedUpdateWithoutFieldsInput>
}

export type TiddlersUpdateWithoutFieldsInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bag?: Prisma.BagsUpdateOneRequiredWithoutTiddlersNestedInput
}

export type TiddlersUncheckedUpdateWithoutFieldsInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TiddlersCreateManyBagInput = {
  revision_id?: string
  title: string
  is_deleted: boolean
  attachment_hash?: string | null
}

export type TiddlersUpdateWithoutBagInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fields?: Prisma.FieldsUpdateManyWithoutTiddlerNestedInput
}

export type TiddlersUncheckedUpdateWithoutBagInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fields?: Prisma.FieldsUncheckedUpdateManyWithoutTiddlerNestedInput
}

export type TiddlersUncheckedUpdateManyWithoutBagInput = {
  revision_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  is_deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  attachment_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TiddlersCountOutputType
 */

export type TiddlersCountOutputType = {
  fields: number
}

export type TiddlersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fields?: boolean | TiddlersCountOutputTypeCountFieldsArgs
}

/**
 * TiddlersCountOutputType without action
 */
export type TiddlersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlersCountOutputType
   */
  select?: Prisma.TiddlersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TiddlersCountOutputType without action
 */
export type TiddlersCountOutputTypeCountFieldsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldsWhereInput
}


export type TiddlersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  revision_id?: boolean
  bag_id?: boolean
  title?: boolean
  is_deleted?: boolean
  attachment_hash?: boolean
  fields?: boolean | Prisma.Tiddlers$fieldsArgs<ExtArgs>
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TiddlersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddlers"]>

export type TiddlersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  revision_id?: boolean
  bag_id?: boolean
  title?: boolean
  is_deleted?: boolean
  attachment_hash?: boolean
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddlers"]>

export type TiddlersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  revision_id?: boolean
  bag_id?: boolean
  title?: boolean
  is_deleted?: boolean
  attachment_hash?: boolean
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddlers"]>

export type TiddlersSelectScalar = {
  revision_id?: boolean
  bag_id?: boolean
  title?: boolean
  is_deleted?: boolean
  attachment_hash?: boolean
}

export type TiddlersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"revision_id" | "bag_id" | "title" | "is_deleted" | "attachment_hash", ExtArgs["result"]["tiddlers"]>
export type TiddlersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fields?: boolean | Prisma.Tiddlers$fieldsArgs<ExtArgs>
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TiddlersCountOutputTypeDefaultArgs<ExtArgs>
}
export type TiddlersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
}
export type TiddlersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagsDefaultArgs<ExtArgs>
}

export type $TiddlersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tiddlers"
  objects: {
    fields: Prisma.$FieldsPayload<ExtArgs>[]
    bag: Prisma.$BagsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    revision_id: string
    bag_id: string
    title: string
    is_deleted: boolean
    attachment_hash: string | null
  }, ExtArgs["result"]["tiddlers"]>
  composites: {}
}

export type TiddlersGetPayload<S extends boolean | null | undefined | TiddlersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TiddlersPayload, S>

export type TiddlersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TiddlersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TiddlersCountAggregateInputType | true
  }

export interface TiddlersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tiddlers'], meta: { name: 'Tiddlers' } }
  /**
   * Find zero or one Tiddlers that matches the filter.
   * @param {TiddlersFindUniqueArgs} args - Arguments to find a Tiddlers
   * @example
   * // Get one Tiddlers
   * const tiddlers = await prisma.tiddlers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TiddlersFindUniqueArgs>(args: Prisma.SelectSubset<T, TiddlersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tiddlers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TiddlersFindUniqueOrThrowArgs} args - Arguments to find a Tiddlers
   * @example
   * // Get one Tiddlers
   * const tiddlers = await prisma.tiddlers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TiddlersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TiddlersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tiddlers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersFindFirstArgs} args - Arguments to find a Tiddlers
   * @example
   * // Get one Tiddlers
   * const tiddlers = await prisma.tiddlers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TiddlersFindFirstArgs>(args?: Prisma.SelectSubset<T, TiddlersFindFirstArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tiddlers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersFindFirstOrThrowArgs} args - Arguments to find a Tiddlers
   * @example
   * // Get one Tiddlers
   * const tiddlers = await prisma.tiddlers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TiddlersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TiddlersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tiddlers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tiddlers
   * const tiddlers = await prisma.tiddlers.findMany()
   * 
   * // Get first 10 Tiddlers
   * const tiddlers = await prisma.tiddlers.findMany({ take: 10 })
   * 
   * // Only select the `revision_id`
   * const tiddlersWithRevision_idOnly = await prisma.tiddlers.findMany({ select: { revision_id: true } })
   * 
   */
  findMany<T extends TiddlersFindManyArgs>(args?: Prisma.SelectSubset<T, TiddlersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tiddlers.
   * @param {TiddlersCreateArgs} args - Arguments to create a Tiddlers.
   * @example
   * // Create one Tiddlers
   * const Tiddlers = await prisma.tiddlers.create({
   *   data: {
   *     // ... data to create a Tiddlers
   *   }
   * })
   * 
   */
  create<T extends TiddlersCreateArgs>(args: Prisma.SelectSubset<T, TiddlersCreateArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tiddlers.
   * @param {TiddlersCreateManyArgs} args - Arguments to create many Tiddlers.
   * @example
   * // Create many Tiddlers
   * const tiddlers = await prisma.tiddlers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TiddlersCreateManyArgs>(args?: Prisma.SelectSubset<T, TiddlersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tiddlers and returns the data saved in the database.
   * @param {TiddlersCreateManyAndReturnArgs} args - Arguments to create many Tiddlers.
   * @example
   * // Create many Tiddlers
   * const tiddlers = await prisma.tiddlers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tiddlers and only return the `revision_id`
   * const tiddlersWithRevision_idOnly = await prisma.tiddlers.createManyAndReturn({
   *   select: { revision_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TiddlersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TiddlersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tiddlers.
   * @param {TiddlersDeleteArgs} args - Arguments to delete one Tiddlers.
   * @example
   * // Delete one Tiddlers
   * const Tiddlers = await prisma.tiddlers.delete({
   *   where: {
   *     // ... filter to delete one Tiddlers
   *   }
   * })
   * 
   */
  delete<T extends TiddlersDeleteArgs>(args: Prisma.SelectSubset<T, TiddlersDeleteArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tiddlers.
   * @param {TiddlersUpdateArgs} args - Arguments to update one Tiddlers.
   * @example
   * // Update one Tiddlers
   * const tiddlers = await prisma.tiddlers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TiddlersUpdateArgs>(args: Prisma.SelectSubset<T, TiddlersUpdateArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tiddlers.
   * @param {TiddlersDeleteManyArgs} args - Arguments to filter Tiddlers to delete.
   * @example
   * // Delete a few Tiddlers
   * const { count } = await prisma.tiddlers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TiddlersDeleteManyArgs>(args?: Prisma.SelectSubset<T, TiddlersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tiddlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tiddlers
   * const tiddlers = await prisma.tiddlers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TiddlersUpdateManyArgs>(args: Prisma.SelectSubset<T, TiddlersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tiddlers and returns the data updated in the database.
   * @param {TiddlersUpdateManyAndReturnArgs} args - Arguments to update many Tiddlers.
   * @example
   * // Update many Tiddlers
   * const tiddlers = await prisma.tiddlers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tiddlers and only return the `revision_id`
   * const tiddlersWithRevision_idOnly = await prisma.tiddlers.updateManyAndReturn({
   *   select: { revision_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TiddlersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TiddlersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tiddlers.
   * @param {TiddlersUpsertArgs} args - Arguments to update or create a Tiddlers.
   * @example
   * // Update or create a Tiddlers
   * const tiddlers = await prisma.tiddlers.upsert({
   *   create: {
   *     // ... data to create a Tiddlers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tiddlers we want to update
   *   }
   * })
   */
  upsert<T extends TiddlersUpsertArgs>(args: Prisma.SelectSubset<T, TiddlersUpsertArgs<ExtArgs>>): Prisma.Prisma__TiddlersClient<runtime.Types.Result.GetResult<Prisma.$TiddlersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tiddlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersCountArgs} args - Arguments to filter Tiddlers to count.
   * @example
   * // Count the number of Tiddlers
   * const count = await prisma.tiddlers.count({
   *   where: {
   *     // ... the filter for the Tiddlers we want to count
   *   }
   * })
  **/
  count<T extends TiddlersCountArgs>(
    args?: Prisma.Subset<T, TiddlersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TiddlersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tiddlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TiddlersAggregateArgs>(args: Prisma.Subset<T, TiddlersAggregateArgs>): Prisma.PrismaPromise<GetTiddlersAggregateType<T>>

  /**
   * Group by Tiddlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TiddlersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TiddlersGroupByArgs['orderBy'] }
      : { orderBy?: TiddlersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TiddlersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTiddlersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tiddlers model
 */
readonly fields: TiddlersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tiddlers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TiddlersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fields<T extends Prisma.Tiddlers$fieldsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tiddlers$fieldsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  bag<T extends Prisma.BagsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BagsDefaultArgs<ExtArgs>>): Prisma.Prisma__BagsClient<runtime.Types.Result.GetResult<Prisma.$BagsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tiddlers model
 */
export interface TiddlersFieldRefs {
  readonly revision_id: Prisma.FieldRef<"Tiddlers", 'String'>
  readonly bag_id: Prisma.FieldRef<"Tiddlers", 'String'>
  readonly title: Prisma.FieldRef<"Tiddlers", 'String'>
  readonly is_deleted: Prisma.FieldRef<"Tiddlers", 'Boolean'>
  readonly attachment_hash: Prisma.FieldRef<"Tiddlers", 'String'>
}
    

// Custom InputTypes
/**
 * Tiddlers findUnique
 */
export type TiddlersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * Filter, which Tiddlers to fetch.
   */
  where: Prisma.TiddlersWhereUniqueInput
}

/**
 * Tiddlers findUniqueOrThrow
 */
export type TiddlersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * Filter, which Tiddlers to fetch.
   */
  where: Prisma.TiddlersWhereUniqueInput
}

/**
 * Tiddlers findFirst
 */
export type TiddlersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * Filter, which Tiddlers to fetch.
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlersOrderByWithRelationInput | Prisma.TiddlersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tiddlers.
   */
  cursor?: Prisma.TiddlersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tiddlers.
   */
  distinct?: Prisma.TiddlersScalarFieldEnum | Prisma.TiddlersScalarFieldEnum[]
}

/**
 * Tiddlers findFirstOrThrow
 */
export type TiddlersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * Filter, which Tiddlers to fetch.
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlersOrderByWithRelationInput | Prisma.TiddlersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tiddlers.
   */
  cursor?: Prisma.TiddlersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tiddlers.
   */
  distinct?: Prisma.TiddlersScalarFieldEnum | Prisma.TiddlersScalarFieldEnum[]
}

/**
 * Tiddlers findMany
 */
export type TiddlersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * Filter, which Tiddlers to fetch.
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlersOrderByWithRelationInput | Prisma.TiddlersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tiddlers.
   */
  cursor?: Prisma.TiddlersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  distinct?: Prisma.TiddlersScalarFieldEnum | Prisma.TiddlersScalarFieldEnum[]
}

/**
 * Tiddlers create
 */
export type TiddlersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * The data needed to create a Tiddlers.
   */
  data: Prisma.XOR<Prisma.TiddlersCreateInput, Prisma.TiddlersUncheckedCreateInput>
}

/**
 * Tiddlers createMany
 */
export type TiddlersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tiddlers.
   */
  data: Prisma.TiddlersCreateManyInput | Prisma.TiddlersCreateManyInput[]
}

/**
 * Tiddlers createManyAndReturn
 */
export type TiddlersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * The data used to create many Tiddlers.
   */
  data: Prisma.TiddlersCreateManyInput | Prisma.TiddlersCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Tiddlers update
 */
export type TiddlersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * The data needed to update a Tiddlers.
   */
  data: Prisma.XOR<Prisma.TiddlersUpdateInput, Prisma.TiddlersUncheckedUpdateInput>
  /**
   * Choose, which Tiddlers to update.
   */
  where: Prisma.TiddlersWhereUniqueInput
}

/**
 * Tiddlers updateMany
 */
export type TiddlersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tiddlers.
   */
  data: Prisma.XOR<Prisma.TiddlersUpdateManyMutationInput, Prisma.TiddlersUncheckedUpdateManyInput>
  /**
   * Filter which Tiddlers to update
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * Limit how many Tiddlers to update.
   */
  limit?: number
}

/**
 * Tiddlers updateManyAndReturn
 */
export type TiddlersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * The data used to update Tiddlers.
   */
  data: Prisma.XOR<Prisma.TiddlersUpdateManyMutationInput, Prisma.TiddlersUncheckedUpdateManyInput>
  /**
   * Filter which Tiddlers to update
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * Limit how many Tiddlers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Tiddlers upsert
 */
export type TiddlersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * The filter to search for the Tiddlers to update in case it exists.
   */
  where: Prisma.TiddlersWhereUniqueInput
  /**
   * In case the Tiddlers found by the `where` argument doesn't exist, create a new Tiddlers with this data.
   */
  create: Prisma.XOR<Prisma.TiddlersCreateInput, Prisma.TiddlersUncheckedCreateInput>
  /**
   * In case the Tiddlers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TiddlersUpdateInput, Prisma.TiddlersUncheckedUpdateInput>
}

/**
 * Tiddlers delete
 */
export type TiddlersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
  /**
   * Filter which Tiddlers to delete.
   */
  where: Prisma.TiddlersWhereUniqueInput
}

/**
 * Tiddlers deleteMany
 */
export type TiddlersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tiddlers to delete
   */
  where?: Prisma.TiddlersWhereInput
  /**
   * Limit how many Tiddlers to delete.
   */
  limit?: number
}

/**
 * Tiddlers.fields
 */
export type Tiddlers$fieldsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fields
   */
  select?: Prisma.FieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fields
   */
  omit?: Prisma.FieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldsInclude<ExtArgs> | null
  where?: Prisma.FieldsWhereInput
  orderBy?: Prisma.FieldsOrderByWithRelationInput | Prisma.FieldsOrderByWithRelationInput[]
  cursor?: Prisma.FieldsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * Tiddlers without action
 */
export type TiddlersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddlers
   */
  select?: Prisma.TiddlersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddlers
   */
  omit?: Prisma.TiddlersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlersInclude<ExtArgs> | null
}
