
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Settings: 'Settings',
  Recipes: 'Recipes',
  RecipeAcl: 'RecipeAcl',
  Recipe_bags: 'Recipe_bags',
  Bags: 'Bags',
  BagAcl: 'BagAcl',
  Tiddlers: 'Tiddlers',
  Fields: 'Fields',
  Roles: 'Roles',
  Users: 'Users',
  Sessions: 'Sessions'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const SettingsScalarFieldEnum = {
  key: 'key',
  value: 'value'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const RecipesScalarFieldEnum = {
  recipe_id: 'recipe_id',
  recipe_name: 'recipe_name',
  description: 'description',
  owner_id: 'owner_id',
  plugin_names: 'plugin_names',
  skip_required_plugins: 'skip_required_plugins',
  skip_core: 'skip_core',
  preload_store: 'preload_store',
  custom_wiki: 'custom_wiki'
} as const

export type RecipesScalarFieldEnum = (typeof RecipesScalarFieldEnum)[keyof typeof RecipesScalarFieldEnum]


export const RecipeAclScalarFieldEnum = {
  acl_id: 'acl_id',
  role_id: 'role_id',
  permission: 'permission',
  recipe_id: 'recipe_id'
} as const

export type RecipeAclScalarFieldEnum = (typeof RecipeAclScalarFieldEnum)[keyof typeof RecipeAclScalarFieldEnum]


export const Recipe_bagsScalarFieldEnum = {
  recipe_id: 'recipe_id',
  bag_id: 'bag_id',
  position: 'position',
  with_acl: 'with_acl',
  load_modules: 'load_modules'
} as const

export type Recipe_bagsScalarFieldEnum = (typeof Recipe_bagsScalarFieldEnum)[keyof typeof Recipe_bagsScalarFieldEnum]


export const BagsScalarFieldEnum = {
  bag_id: 'bag_id',
  bag_name: 'bag_name',
  description: 'description',
  owner_id: 'owner_id'
} as const

export type BagsScalarFieldEnum = (typeof BagsScalarFieldEnum)[keyof typeof BagsScalarFieldEnum]


export const BagAclScalarFieldEnum = {
  acl_id: 'acl_id',
  bag_id: 'bag_id',
  role_id: 'role_id',
  permission: 'permission'
} as const

export type BagAclScalarFieldEnum = (typeof BagAclScalarFieldEnum)[keyof typeof BagAclScalarFieldEnum]


export const TiddlersScalarFieldEnum = {
  revision_id: 'revision_id',
  bag_id: 'bag_id',
  title: 'title',
  is_deleted: 'is_deleted',
  attachment_hash: 'attachment_hash'
} as const

export type TiddlersScalarFieldEnum = (typeof TiddlersScalarFieldEnum)[keyof typeof TiddlersScalarFieldEnum]


export const FieldsScalarFieldEnum = {
  revision_id: 'revision_id',
  field_name: 'field_name',
  field_value: 'field_value'
} as const

export type FieldsScalarFieldEnum = (typeof FieldsScalarFieldEnum)[keyof typeof FieldsScalarFieldEnum]


export const RolesScalarFieldEnum = {
  role_id: 'role_id',
  role_name: 'role_name',
  description: 'description'
} as const

export type RolesScalarFieldEnum = (typeof RolesScalarFieldEnum)[keyof typeof RolesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  user_id: 'user_id',
  username: 'username',
  email: 'email',
  password: 'password',
  created_at: 'created_at',
  last_login: 'last_login'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SessionsScalarFieldEnum = {
  session_id: 'session_id',
  created_at: 'created_at',
  last_accessed: 'last_accessed',
  session_key: 'session_key',
  user_id: 'user_id'
} as const

export type SessionsScalarFieldEnum = (typeof SessionsScalarFieldEnum)[keyof typeof SessionsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

